#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2022.1 (64-bit)
#
# Filename    : base.sh
# Simulator   : Cadence Xcelium Parallel Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Wed Oct 11 04:00:04 +0800 2023
# SW Build 3526262 on Mon Apr 18 15:48:16 MDT 2022
#
# Tool Version Limit: 2022.04 
#
# usage: base.sh [-help]
# usage: base.sh [-lib_map_path]
# usage: base.sh [-noclean_files]
# usage: base.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'base.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Set the compiled library directory path
ref_lib_dir="."

# Set xrun options
xrun_opts="-64bit -v93 -relax -access +rwc -namemap_mixgen"

# Design libraries
design_libs=(xilinx_vip xpm lib_pkg_v1_0_2 lib_cdc_v1_0_2 axi_lite_ipif_v3_0_4 interrupt_control_v3_1_4 axi_iic_v2_1_2 xil_defaultlib axi_intc_v4_1_17 generic_baseblocks_v2_1_0 axi_infrastructure_v1_1_0 axi_register_slice_v2_1_26 fifo_generator_v13_2_7 axi_data_fifo_v2_1_25 axi_crossbar_v2_1_27 axi_protocol_converter_v2_1_26 axi_clock_converter_v2_1_25 blk_mem_gen_v8_4_5 axi_dwidth_converter_v2_1_26 xlconstant_v1_1_7 proc_sys_reset_v5_0_13 smartconnect_v1_0 axi_vip_v1_1_12 xlconcat_v2_1_4 axi_gpio_v2_0_28 xlslice_v1_0_2 lmb_v10_v3_0_12 lmb_bram_if_cntlr_v4_0_21 microblaze_v11_0_9 axi_bram_ctrl_v4_1_6 axi_timer_v2_0_28 dist_mem_gen_v8_0_13 lib_srl_fifo_v1_0_2 lib_fifo_v1_0_16 axi_quad_spi_v3_2_25 axi_uartlite_v2_0_30 mdm_v3_2_23 lib_bmg_v1_0_14 axi_datamover_v5_1_28 axi_vdma_v6_3_14 axis_infrastructure_v1_1_0 axis_register_slice_v1_1_26 axis_subset_converter_v1_1_26 v_demosaic_v1_1_5 v_gamma_lut_v1_1_5 mipi_csi2_rx_ctrl_v1_0_8 high_speed_selectio_wiz_v3_6_3 mipi_dphy_v4_3_4 axis_dwidth_converter_v1_1_25 axis_switch_v1_1_26 vfb_v1_0_20 v_csc_v1_1_5 zynq_ultra_ps_e_vip_v1_0_12 xbip_utils_v3_0_10 dfx_axi_shutdown_manager_v1_0_0 axi_sg_v4_1_15 axi_dma_v7_1_27 axis_data_fifo_v2_0_8 v_hdmi_rx_v3_0_0 v_vid_in_axi4s_v5_0_1 util_vector_logic_v2_0_2 v_hdmi_tx_v3_0_0 v_tc_v6_2_4 v_tc_v6_1_13 v_vid_in_axi4s_v4_0_9 v_axi4s_vid_out_v4_0_14 gtwizard_ultrascale_v1_7_13 vid_phy_controller_v2_2_13)

# Simulation root library directory
sim_lib_dir="xcelium_lib"

# Script info
echo -e "base.sh - Script generated by export_simulation (Vivado v2022.1 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  execute
}

# RUN_STEP: <execute>
execute()
{
  xrun $xrun_opts \
       -reflib "$ref_lib_dir/unisim:unisim" \
       -reflib "$ref_lib_dir/unisims_ver:unisims_ver" \
       -reflib "$ref_lib_dir/secureip:secureip" \
       -reflib "$ref_lib_dir/unimacro:unimacro" \
       -reflib "$ref_lib_dir/unimacro_ver:unimacro_ver" \
       -top xil_defaultlib.base \
       -f run.f \
       -top glbl \
       +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" \
       +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/f0b6/hdl/verilog" \
       +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/66be/hdl/verilog" \
       +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/4e49" \
       +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/fc4b/hdl" \
       +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8713/hdl" \
       +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/9758/hdl" \
       +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8cdf/hdl" \
       +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/4683/hdl/src/verilog" \
       +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" \
       +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/f0b6/hdl/verilog" \
       +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/66be/hdl/verilog" \
       +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/4e49" \
       +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/fc4b/hdl" \
       +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/8713/hdl" \
       +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/9758/hdl" \
       +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_2_v1_0/src" \
       +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/8cdf/hdl" \
       +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_trace_cntrl_64_0_0/drivers/trace_cntrl_64_v1_4/src" \
       +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_trace_cntrl_32_0_0/drivers/trace_cntrl_32_v1_4/src" \
       +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_trace_cntrl_32_0_1/drivers/trace_cntrl_32_v1_4/src" \
       +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_2_v1_0/src" \
       +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_1/drivers/pixel_pack_2_v1_0/src" \
       +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_2_v1_0/src" \
       +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_2_v1_0/src" \
       +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/4683/hdl/src/verilog" \
       +incdir+"D:/VIVADO/Vivado/2022.1/data/xilinx_vip/include"
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./base.sh -help\" for more information)\n"
        exit 1
      else
        ref_lib_dir=$2
      fi
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(xmsim.key xrun.key xrun.log waves.shm xrun.history .simvision xcelium.d xcelium)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./base.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: base.sh [-help]\n\
Usage: base.sh [-lib_map_path]\n\
Usage: base.sh [-reset_run]\n\
Usage: base.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
