// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="pixel_pack_2_pixel_pack_2,hls_ip_2020_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu7ev-ffvc1156-2-i,HLS_INPUT_CLOCK=3.300000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=1.721000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1429,HLS_SYN_LUT=1054,HLS_VERSION=2020_2}" *)

module pixel_pack_2 (
        ap_clk,
        ap_rst_n,
        stream_in_48_TDATA,
        stream_in_48_TVALID,
        stream_in_48_TREADY,
        stream_in_48_TKEEP,
        stream_in_48_TSTRB,
        stream_in_48_TUSER,
        stream_in_48_TLAST,
        stream_out_64_TDATA,
        stream_out_64_TVALID,
        stream_out_64_TREADY,
        stream_out_64_TKEEP,
        stream_out_64_TSTRB,
        stream_out_64_TUSER,
        stream_out_64_TLAST,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP
);

parameter    ap_ST_fsm_state1 = 19'd1;
parameter    ap_ST_fsm_state2 = 19'd2;
parameter    ap_ST_fsm_pp0_stage0 = 19'd4;
parameter    ap_ST_fsm_pp0_stage1 = 19'd8;
parameter    ap_ST_fsm_state6 = 19'd16;
parameter    ap_ST_fsm_pp1_stage0 = 19'd32;
parameter    ap_ST_fsm_pp1_stage1 = 19'd64;
parameter    ap_ST_fsm_pp2_stage0 = 19'd128;
parameter    ap_ST_fsm_pp2_stage1 = 19'd256;
parameter    ap_ST_fsm_pp2_stage2 = 19'd512;
parameter    ap_ST_fsm_pp2_stage3 = 19'd1024;
parameter    ap_ST_fsm_state15 = 19'd2048;
parameter    ap_ST_fsm_pp3_stage0 = 19'd4096;
parameter    ap_ST_fsm_state18 = 19'd8192;
parameter    ap_ST_fsm_pp4_stage0 = 19'd16384;
parameter    ap_ST_fsm_pp4_stage1 = 19'd32768;
parameter    ap_ST_fsm_pp4_stage2 = 19'd65536;
parameter    ap_ST_fsm_pp4_stage3 = 19'd131072;
parameter    ap_ST_fsm_state26 = 19'd262144;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 5;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [47:0] stream_in_48_TDATA;
input   stream_in_48_TVALID;
output   stream_in_48_TREADY;
input  [5:0] stream_in_48_TKEEP;
input  [5:0] stream_in_48_TSTRB;
input  [0:0] stream_in_48_TUSER;
input  [0:0] stream_in_48_TLAST;
output  [63:0] stream_out_64_TDATA;
output   stream_out_64_TVALID;
input   stream_out_64_TREADY;
output  [7:0] stream_out_64_TKEEP;
output  [7:0] stream_out_64_TSTRB;
output  [0:0] stream_out_64_TUSER;
output  [0:0] stream_out_64_TLAST;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;

 reg    ap_rst_n_inv;
wire   [31:0] mode;
reg   [31:0] mode_0_data_reg;
reg    mode_0_vld_reg;
reg    mode_0_ack_out;
wire   [7:0] alpha;
reg   [7:0] alpha_0_data_reg;
reg    alpha_0_vld_reg;
reg    alpha_0_ack_out;
reg    stream_in_48_TDATA_blk_n;
(* fsm_encoding = "none" *) reg   [18:0] ap_CS_fsm;
wire    ap_CS_fsm_pp4_stage0;
reg    ap_enable_reg_pp4_iter0;
wire    ap_block_pp4_stage0;
reg   [0:0] ap_phi_mux_delayed_last_phi_fu_431_p4;
reg   [0:0] ap_phi_mux_last_phi_fu_444_p4;
wire    ap_CS_fsm_pp4_stage1;
wire    ap_block_pp4_stage1;
reg   [0:0] delayed_last_reg_427;
reg   [0:0] last_2_0_reg_452;
wire    ap_CS_fsm_pp4_stage2;
wire    ap_block_pp4_stage2;
reg   [0:0] last_2_1_reg_496;
wire    ap_CS_fsm_pp4_stage3;
wire    ap_block_pp4_stage3;
reg   [0:0] last_2_2_reg_540;
wire    ap_CS_fsm_pp3_stage0;
reg    ap_enable_reg_pp3_iter0;
wire    ap_block_pp3_stage0;
wire    ap_CS_fsm_pp2_stage0;
reg    ap_enable_reg_pp2_iter0;
wire    ap_block_pp2_stage0;
reg   [0:0] ap_phi_mux_delayed_last_1_phi_fu_231_p4;
reg   [0:0] ap_phi_mux_last_4_phi_fu_244_p4;
wire    ap_CS_fsm_pp2_stage1;
wire    ap_block_pp2_stage1;
reg   [0:0] delayed_last_1_reg_227;
reg   [0:0] last_6_0_reg_252;
wire    ap_CS_fsm_pp2_stage2;
wire    ap_block_pp2_stage2;
reg   [0:0] last_6_1_reg_286;
wire    ap_CS_fsm_pp2_stage3;
wire    ap_block_pp2_stage3;
reg   [0:0] last_6_2_reg_319;
wire    ap_CS_fsm_pp1_stage0;
reg    ap_enable_reg_pp1_iter0;
wire    ap_block_pp1_stage0;
wire    ap_CS_fsm_pp1_stage1;
wire    ap_block_pp1_stage1;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1;
reg    stream_out_64_TDATA_blk_n;
reg   [0:0] last_reg_439;
reg    ap_enable_reg_pp4_iter1;
reg   [0:0] last_reg_439_pp4_iter1_reg;
reg    ap_enable_reg_pp3_iter1;
reg   [0:0] last_4_reg_239;
reg    ap_enable_reg_pp2_iter1;
reg    ap_enable_reg_pp1_iter1;
reg    ap_enable_reg_pp0_iter1;
reg   [63:0] data_V_9_3_reg_350;
reg   [0:0] last_6_3_reg_377;
reg    ap_predicate_op209_read_state19;
reg    ap_block_state19_pp4_stage0_iter0;
reg    ap_block_state23_pp4_stage0_iter1;
reg    ap_block_state23_io;
reg    ap_block_pp4_stage0_11001;
reg    ap_predicate_op223_read_state20;
reg    ap_block_state20_pp4_stage1_iter0;
reg    ap_block_state24_pp4_stage1_iter1;
reg    ap_block_state24_io;
reg    ap_block_pp4_stage1_11001;
reg   [191:0] buffer_V_3_3_reg_581;
reg   [3:0] has_last_V_3_3_reg_593;
reg   [3:0] has_user_V_3_3_reg_605;
reg   [0:0] last_2_3_reg_617;
reg   [7:0] alpha_read_reg_1238;
wire    ap_CS_fsm_state2;
wire   [31:0] grp_read_fu_174_p2;
reg   [0:0] empty_38_reg_1248_3;
reg    ap_block_state3_pp0_stage0_iter0;
reg    ap_block_state5_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
wire   [7:0] trunc_ln674_1_fu_739_p1;
reg   [7:0] trunc_ln674_1_reg_1253;
reg   [7:0] p_Result_s_40_reg_1258;
wire   [7:0] grp_fu_673_p4;
reg   [7:0] p_Result_10_reg_1263;
reg   [7:0] p_Result_11_reg_1268;
wire   [0:0] grp_fu_683_p1;
reg    ap_block_state4_pp0_stage1_iter0;
reg    ap_block_pp0_stage1_11001;
wire   [0:0] or_ln111_fu_770_p2;
wire   [63:0] p_Result_25_fu_829_p9;
reg   [0:0] empty_36_reg_1288_3;
reg    ap_block_state7_pp1_stage0_iter0;
reg    ap_block_state9_pp1_stage0_iter1;
reg    ap_block_pp1_stage0_11001;
wire   [15:0] trunc_ln215_fu_846_p1;
reg   [15:0] trunc_ln215_reg_1293;
wire   [15:0] grp_fu_696_p4;
reg   [15:0] p_Result_5_reg_1298;
reg    ap_block_state8_pp1_stage1_iter0;
reg    ap_block_pp1_stage1_11001;
wire   [0:0] or_ln93_fu_857_p2;
wire   [63:0] p_Result_64_1_fu_868_p5;
reg    ap_predicate_op127_read_state10;
reg    ap_block_state10_pp2_stage0_iter0;
reg    ap_block_state14_pp2_stage0_iter1;
reg    ap_block_state14_io;
reg    ap_block_pp2_stage0_11001;
wire   [63:0] p_Result_21_fu_891_p5;
wire   [0:0] or_ln72_fu_907_p2;
reg    ap_predicate_op141_read_state11;
reg    ap_block_state11_pp2_stage1_iter0;
reg    ap_block_pp2_stage1_11001;
wire   [63:0] p_Result_60_1_fu_925_p5;
wire   [0:0] or_ln72_1_fu_941_p2;
reg    ap_predicate_op155_read_state12;
reg    ap_block_state12_pp2_stage2_iter0;
reg    ap_block_pp2_stage2_11001;
wire   [63:0] p_Result_60_2_fu_959_p5;
reg    ap_block_state16_pp3_stage0_iter0;
reg    ap_block_state17_pp3_stage0_iter1;
reg    ap_block_pp3_stage0_11001;
wire   [63:0] p_Result_24_fu_1021_p5;
wire   [191:0] p_Result_s_fu_1032_p5;
wire   [3:0] tmp_4_fu_1044_p4;
wire   [3:0] tmp_5_fu_1054_p4;
wire   [191:0] p_Result_1_fu_1064_p5;
wire   [3:0] tmp_6_fu_1076_p4;
wire   [3:0] tmp_7_fu_1086_p4;
wire   [191:0] p_Result_2_fu_1096_p5;
reg    ap_predicate_op236_read_state21;
reg    ap_block_state21_pp4_stage2_iter0;
reg    ap_block_state25_pp4_stage2_iter1;
reg    ap_block_state25_io;
reg    ap_block_pp4_stage2_11001;
wire   [3:0] tmp_8_fu_1108_p4;
wire   [3:0] tmp_9_fu_1118_p4;
wire   [63:0] trunc_ln674_7_fu_1163_p1;
reg    ap_predicate_op249_read_state22;
reg    ap_predicate_op265_write_state22;
reg    ap_block_state22_pp4_stage3_iter0;
reg    ap_block_state22_io;
reg    ap_block_pp4_stage3_11001;
reg   [63:0] p_Result_48_1_reg_1423;
reg   [0:0] p_Result_49_1_reg_1428;
reg   [0:0] p_Result_50_1_reg_1433;
reg   [63:0] p_Result_48_2_reg_1438;
reg   [0:0] p_Result_49_2_reg_1443;
reg   [0:0] p_Result_50_2_reg_1448;
reg    ap_block_pp0_stage1_subdone;
reg    ap_condition_pp0_flush_enable;
reg    ap_block_pp0_stage0_subdone;
reg    ap_block_pp1_stage1_subdone;
reg    ap_condition_pp1_flush_enable;
reg    ap_block_pp1_stage0_subdone;
reg    ap_block_pp2_stage0_subdone;
reg    ap_condition_pp2_exit_iter0_state10;
reg    ap_predicate_op169_read_state13;
reg    ap_predicate_op183_write_state13;
reg    ap_block_state13_pp2_stage3_iter0;
reg    ap_block_state13_io;
reg    ap_block_pp2_stage3_subdone;
reg    ap_block_pp3_stage0_subdone;
reg    ap_condition_pp3_flush_enable;
reg    ap_block_pp4_stage0_subdone;
reg    ap_condition_pp4_exit_iter0_state19;
reg    ap_block_pp4_stage3_subdone;
reg    ap_block_pp4_stage2_subdone;
wire   [0:0] ap_phi_reg_pp2_iter0_last_6_0_reg_252;
reg   [63:0] ap_phi_reg_pp2_iter0_data_V_9_0_reg_263;
reg   [0:0] ap_phi_reg_pp2_iter0_user_6_0_reg_274;
wire   [0:0] ap_phi_reg_pp2_iter0_last_6_1_reg_286;
reg   [63:0] ap_phi_reg_pp2_iter0_data_V_9_1_reg_297;
reg   [0:0] ap_phi_reg_pp2_iter0_user_6_1_reg_308;
wire   [0:0] ap_phi_reg_pp2_iter0_last_6_2_reg_319;
reg   [63:0] ap_phi_reg_pp2_iter0_data_V_9_2_reg_330;
reg    ap_block_pp2_stage3_11001;
reg   [0:0] ap_phi_reg_pp2_iter0_user_6_2_reg_340;
reg   [63:0] ap_phi_mux_data_V_9_3_phi_fu_355_p4;
wire   [63:0] p_Result_60_3_fu_994_p5;
wire   [63:0] ap_phi_reg_pp2_iter0_data_V_9_3_reg_350;
reg   [0:0] ap_phi_mux_user_6_3_phi_fu_368_p4;
wire   [0:0] or_ln72_2_fu_975_p2;
wire   [0:0] ap_phi_reg_pp2_iter0_user_6_3_reg_364;
reg   [0:0] ap_phi_mux_last_6_3_phi_fu_382_p4;
wire   [0:0] ap_phi_reg_pp2_iter0_last_6_3_reg_377;
wire   [0:0] ap_phi_reg_pp4_iter0_last_2_0_reg_452;
reg   [191:0] ap_phi_reg_pp4_iter0_buffer_V_3_0_reg_463;
reg   [3:0] ap_phi_reg_pp4_iter0_has_last_V_3_0_reg_474;
reg   [3:0] ap_phi_reg_pp4_iter0_has_user_V_3_0_reg_485;
wire   [0:0] ap_phi_reg_pp4_iter0_last_2_1_reg_496;
reg   [191:0] ap_phi_reg_pp4_iter0_buffer_V_3_1_reg_507;
reg   [3:0] ap_phi_reg_pp4_iter0_has_last_V_3_1_reg_518;
reg   [3:0] ap_phi_reg_pp4_iter0_has_user_V_3_1_reg_529;
wire   [0:0] ap_phi_reg_pp4_iter0_last_2_2_reg_540;
reg   [191:0] ap_phi_reg_pp4_iter0_buffer_V_3_2_reg_551;
reg   [3:0] ap_phi_reg_pp4_iter0_has_last_V_3_2_reg_561;
reg   [3:0] ap_phi_reg_pp4_iter0_has_user_V_3_2_reg_571;
reg   [191:0] ap_phi_mux_buffer_V_3_3_phi_fu_585_p4;
wire   [191:0] p_Result_3_fu_1128_p5;
wire   [191:0] ap_phi_reg_pp4_iter0_buffer_V_3_3_reg_581;
reg   [3:0] ap_phi_mux_has_last_V_3_3_phi_fu_597_p4;
wire   [3:0] tmp_11_fu_1152_p4;
wire   [3:0] ap_phi_reg_pp4_iter0_has_last_V_3_3_reg_593;
reg   [3:0] ap_phi_mux_has_user_V_3_3_phi_fu_609_p4;
wire   [3:0] tmp_10_fu_1141_p4;
wire   [3:0] ap_phi_reg_pp4_iter0_has_user_V_3_3_reg_605;
wire   [0:0] ap_phi_reg_pp4_iter0_last_2_3_reg_617;
reg    ap_block_pp0_stage1_01001;
reg    ap_block_pp1_stage1_01001;
reg    ap_block_pp2_stage3_01001;
reg    ap_block_pp3_stage0_01001;
reg    ap_block_pp4_stage3_01001;
reg    ap_block_pp4_stage0_01001;
reg    ap_block_pp4_stage1_01001;
wire   [7:0] grp_fu_633_p4;
wire   [7:0] grp_fu_643_p4;
wire   [8:0] zext_ln358_1_fu_715_p1;
wire   [8:0] zext_ln358_fu_711_p1;
wire   [7:0] grp_fu_653_p4;
wire   [7:0] grp_fu_663_p4;
wire   [8:0] zext_ln358_3_fu_729_p1;
wire   [8:0] zext_ln358_2_fu_725_p1;
wire   [8:0] out_c1_V_fu_719_p2;
wire   [8:0] out_c2_V_fu_733_p2;
wire   [8:0] zext_ln358_5_fu_781_p1;
wire   [8:0] zext_ln358_4_fu_777_p1;
wire   [8:0] zext_ln358_7_fu_795_p1;
wire   [8:0] zext_ln358_6_fu_791_p1;
wire   [8:0] out_c3_V_fu_785_p2;
wire   [8:0] out_c4_V_fu_799_p2;
wire   [7:0] p_Result_18_fu_819_p4;
wire   [7:0] p_Result_16_fu_809_p4;
wire   [7:0] trunc_ln674_2_fu_805_p1;
wire   [15:0] trunc_ln215_1_fu_864_p1;
wire   [7:0] trunc_ln674_3_fu_879_p1;
wire   [15:0] tmp_fu_883_p3;
wire   [7:0] trunc_ln674_4_fu_913_p1;
wire   [15:0] tmp_1_fu_917_p3;
wire   [7:0] trunc_ln674_5_fu_947_p1;
wire   [15:0] tmp_2_fu_951_p3;
wire   [7:0] trunc_ln674_6_fu_982_p1;
wire   [15:0] tmp_3_fu_986_p3;
wire   [23:0] p_Result_4_fu_1011_p4;
wire   [23:0] trunc_ln674_fu_1007_p1;
wire    ap_CS_fsm_state6;
wire    regslice_both_stream_out_64_V_data_V_U_apdone_blk;
reg   [18:0] ap_NS_fsm;
reg    ap_block_pp2_stage1_subdone;
reg    ap_block_pp2_stage2_subdone;
reg    ap_block_pp4_stage1_subdone;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_idle_pp1;
wire    ap_enable_pp1;
reg    ap_idle_pp2;
wire    ap_enable_pp2;
reg    ap_idle_pp3;
wire    ap_enable_pp3;
reg    ap_idle_pp4;
wire    ap_enable_pp4;
wire    regslice_both_stream_in_48_V_data_V_U_apdone_blk;
wire   [47:0] stream_in_48_TDATA_int_regslice;
wire    stream_in_48_TVALID_int_regslice;
reg    stream_in_48_TREADY_int_regslice;
wire    regslice_both_stream_in_48_V_data_V_U_ack_in;
wire    regslice_both_stream_in_48_V_keep_V_U_apdone_blk;
wire   [5:0] stream_in_48_TKEEP_int_regslice;
wire    regslice_both_stream_in_48_V_keep_V_U_vld_out;
wire    regslice_both_stream_in_48_V_keep_V_U_ack_in;
wire    regslice_both_stream_in_48_V_strb_V_U_apdone_blk;
wire   [5:0] stream_in_48_TSTRB_int_regslice;
wire    regslice_both_stream_in_48_V_strb_V_U_vld_out;
wire    regslice_both_stream_in_48_V_strb_V_U_ack_in;
wire    regslice_both_stream_in_48_V_user_V_U_apdone_blk;
wire   [0:0] stream_in_48_TUSER_int_regslice;
wire    regslice_both_stream_in_48_V_user_V_U_vld_out;
wire    regslice_both_stream_in_48_V_user_V_U_ack_in;
wire    regslice_both_stream_in_48_V_last_V_U_apdone_blk;
wire   [0:0] stream_in_48_TLAST_int_regslice;
wire    regslice_both_stream_in_48_V_last_V_U_vld_out;
wire    regslice_both_stream_in_48_V_last_V_U_ack_in;
reg   [63:0] stream_out_64_TDATA_int_regslice;
reg    stream_out_64_TVALID_int_regslice;
wire    stream_out_64_TREADY_int_regslice;
wire    regslice_both_stream_out_64_V_data_V_U_vld_out;
wire    regslice_both_stream_out_64_V_keep_V_U_apdone_blk;
wire    regslice_both_stream_out_64_V_keep_V_U_ack_in_dummy;
wire    regslice_both_stream_out_64_V_keep_V_U_vld_out;
wire    regslice_both_stream_out_64_V_strb_V_U_apdone_blk;
wire    regslice_both_stream_out_64_V_strb_V_U_ack_in_dummy;
wire    regslice_both_stream_out_64_V_strb_V_U_vld_out;
wire    regslice_both_stream_out_64_V_user_V_U_apdone_blk;
reg   [0:0] stream_out_64_TUSER_int_regslice;
wire    regslice_both_stream_out_64_V_user_V_U_ack_in_dummy;
wire    regslice_both_stream_out_64_V_user_V_U_vld_out;
wire    regslice_both_stream_out_64_V_last_V_U_apdone_blk;
reg   [0:0] stream_out_64_TLAST_int_regslice;
wire    regslice_both_stream_out_64_V_last_V_U_ack_in_dummy;
wire    regslice_both_stream_out_64_V_last_V_U_vld_out;
reg    ap_condition_1641;
reg    ap_condition_1645;
reg    ap_condition_1650;
reg    ap_condition_1654;
reg    ap_condition_1658;
reg    ap_condition_1663;
reg    ap_condition_880;
reg    ap_condition_824;
reg    ap_condition_847;
reg    ap_condition_854;
reg    ap_condition_867;
reg    ap_condition_571;
reg    ap_condition_799;
reg    ap_condition_810;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 mode_0_data_reg = 32'd0;
#0 mode_0_vld_reg = 1'b0;
#0 alpha_0_data_reg = 8'd0;
#0 alpha_0_vld_reg = 1'b0;
#0 ap_CS_fsm = 19'd1;
#0 ap_enable_reg_pp4_iter0 = 1'b0;
#0 ap_enable_reg_pp3_iter0 = 1'b0;
#0 ap_enable_reg_pp2_iter0 = 1'b0;
#0 ap_enable_reg_pp1_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp4_iter1 = 1'b0;
#0 ap_enable_reg_pp3_iter1 = 1'b0;
#0 ap_enable_reg_pp2_iter1 = 1'b0;
#0 ap_enable_reg_pp1_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

pixel_pack_2_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .mode(mode),
    .alpha(alpha)
);

pixel_pack_2_regslice_both #(
    .DataWidth( 48 ))
regslice_both_stream_in_48_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_48_TDATA),
    .vld_in(stream_in_48_TVALID),
    .ack_in(regslice_both_stream_in_48_V_data_V_U_ack_in),
    .data_out(stream_in_48_TDATA_int_regslice),
    .vld_out(stream_in_48_TVALID_int_regslice),
    .ack_out(stream_in_48_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_48_V_data_V_U_apdone_blk)
);

pixel_pack_2_regslice_both #(
    .DataWidth( 6 ))
regslice_both_stream_in_48_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_48_TKEEP),
    .vld_in(stream_in_48_TVALID),
    .ack_in(regslice_both_stream_in_48_V_keep_V_U_ack_in),
    .data_out(stream_in_48_TKEEP_int_regslice),
    .vld_out(regslice_both_stream_in_48_V_keep_V_U_vld_out),
    .ack_out(stream_in_48_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_48_V_keep_V_U_apdone_blk)
);

pixel_pack_2_regslice_both #(
    .DataWidth( 6 ))
regslice_both_stream_in_48_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_48_TSTRB),
    .vld_in(stream_in_48_TVALID),
    .ack_in(regslice_both_stream_in_48_V_strb_V_U_ack_in),
    .data_out(stream_in_48_TSTRB_int_regslice),
    .vld_out(regslice_both_stream_in_48_V_strb_V_U_vld_out),
    .ack_out(stream_in_48_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_48_V_strb_V_U_apdone_blk)
);

pixel_pack_2_regslice_both #(
    .DataWidth( 1 ))
regslice_both_stream_in_48_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_48_TUSER),
    .vld_in(stream_in_48_TVALID),
    .ack_in(regslice_both_stream_in_48_V_user_V_U_ack_in),
    .data_out(stream_in_48_TUSER_int_regslice),
    .vld_out(regslice_both_stream_in_48_V_user_V_U_vld_out),
    .ack_out(stream_in_48_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_48_V_user_V_U_apdone_blk)
);

pixel_pack_2_regslice_both #(
    .DataWidth( 1 ))
regslice_both_stream_in_48_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_48_TLAST),
    .vld_in(stream_in_48_TVALID),
    .ack_in(regslice_both_stream_in_48_V_last_V_U_ack_in),
    .data_out(stream_in_48_TLAST_int_regslice),
    .vld_out(regslice_both_stream_in_48_V_last_V_U_vld_out),
    .ack_out(stream_in_48_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_48_V_last_V_U_apdone_blk)
);

pixel_pack_2_regslice_both #(
    .DataWidth( 64 ))
regslice_both_stream_out_64_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_out_64_TDATA_int_regslice),
    .vld_in(stream_out_64_TVALID_int_regslice),
    .ack_in(stream_out_64_TREADY_int_regslice),
    .data_out(stream_out_64_TDATA),
    .vld_out(regslice_both_stream_out_64_V_data_V_U_vld_out),
    .ack_out(stream_out_64_TREADY),
    .apdone_blk(regslice_both_stream_out_64_V_data_V_U_apdone_blk)
);

pixel_pack_2_regslice_both #(
    .DataWidth( 8 ))
regslice_both_stream_out_64_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(8'd0),
    .vld_in(stream_out_64_TVALID_int_regslice),
    .ack_in(regslice_both_stream_out_64_V_keep_V_U_ack_in_dummy),
    .data_out(stream_out_64_TKEEP),
    .vld_out(regslice_both_stream_out_64_V_keep_V_U_vld_out),
    .ack_out(stream_out_64_TREADY),
    .apdone_blk(regslice_both_stream_out_64_V_keep_V_U_apdone_blk)
);

pixel_pack_2_regslice_both #(
    .DataWidth( 8 ))
regslice_both_stream_out_64_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(8'd0),
    .vld_in(stream_out_64_TVALID_int_regslice),
    .ack_in(regslice_both_stream_out_64_V_strb_V_U_ack_in_dummy),
    .data_out(stream_out_64_TSTRB),
    .vld_out(regslice_both_stream_out_64_V_strb_V_U_vld_out),
    .ack_out(stream_out_64_TREADY),
    .apdone_blk(regslice_both_stream_out_64_V_strb_V_U_apdone_blk)
);

pixel_pack_2_regslice_both #(
    .DataWidth( 1 ))
regslice_both_stream_out_64_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_out_64_TUSER_int_regslice),
    .vld_in(stream_out_64_TVALID_int_regslice),
    .ack_in(regslice_both_stream_out_64_V_user_V_U_ack_in_dummy),
    .data_out(stream_out_64_TUSER),
    .vld_out(regslice_both_stream_out_64_V_user_V_U_vld_out),
    .ack_out(stream_out_64_TREADY),
    .apdone_blk(regslice_both_stream_out_64_V_user_V_U_apdone_blk)
);

pixel_pack_2_regslice_both #(
    .DataWidth( 1 ))
regslice_both_stream_out_64_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_out_64_TLAST_int_regslice),
    .vld_in(stream_out_64_TVALID_int_regslice),
    .ack_in(regslice_both_stream_out_64_V_last_V_U_ack_in_dummy),
    .data_out(stream_out_64_TLAST),
    .vld_out(regslice_both_stream_out_64_V_last_V_U_vld_out),
    .ack_out(stream_out_64_TREADY),
    .apdone_blk(regslice_both_stream_out_64_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_pp0_flush_enable)) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((grp_read_fu_174_p2 == 32'd4) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((((ap_enable_reg_pp0_iter0 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone)) | ((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone)))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((grp_read_fu_174_p2 == 32'd4) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter0 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_pp1_flush_enable)) begin
            ap_enable_reg_pp1_iter0 <= 1'b0;
        end else if (((grp_read_fu_174_p2 == 32'd3) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp1_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter1 <= 1'b0;
    end else begin
        if ((((ap_enable_reg_pp1_iter0 == 1'b0) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_subdone)) | ((1'b1 == ap_CS_fsm_pp1_stage1) & (1'b0 == ap_block_pp1_stage1_subdone)))) begin
            ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
        end else if (((grp_read_fu_174_p2 == 32'd3) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp1_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp2_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_condition_pp2_exit_iter0_state10) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_subdone))) begin
            ap_enable_reg_pp2_iter0 <= 1'b0;
        end else if (((grp_read_fu_174_p2 == 32'd2) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp2_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp2_iter1 <= 1'b0;
    end else begin
        if ((((1'b1 == ap_CS_fsm_pp2_stage3) & (1'b0 == ap_block_pp2_stage3_subdone)) | ((1'b1 == ap_CS_fsm_pp2_stage0) & (ap_enable_reg_pp2_iter0 == 1'b0) & (1'b0 == ap_block_pp2_stage0_subdone)))) begin
            ap_enable_reg_pp2_iter1 <= ap_enable_reg_pp2_iter0;
        end else if (((grp_read_fu_174_p2 == 32'd2) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp2_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp3_iter0 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_pp3_flush_enable)) begin
            ap_enable_reg_pp3_iter0 <= 1'b0;
        end else if (((grp_read_fu_174_p2 == 32'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp3_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp3_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp3_stage0_subdone)) begin
            ap_enable_reg_pp3_iter1 <= ap_enable_reg_pp3_iter0;
        end else if (((grp_read_fu_174_p2 == 32'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp3_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp4_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp4_stage0) & (1'b1 == ap_condition_pp4_exit_iter0_state19) & (1'b0 == ap_block_pp4_stage0_subdone))) begin
            ap_enable_reg_pp4_iter0 <= 1'b0;
        end else if (((grp_read_fu_174_p2 == 32'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp4_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp4_iter1 <= 1'b0;
    end else begin
        if ((((ap_enable_reg_pp4_iter0 == 1'b0) & (1'b1 == ap_CS_fsm_pp4_stage2) & (1'b0 == ap_block_pp4_stage2_subdone)) | ((1'b1 == ap_CS_fsm_pp4_stage3) & (1'b0 == ap_block_pp4_stage3_subdone)))) begin
            ap_enable_reg_pp4_iter1 <= ap_enable_reg_pp4_iter0;
        end else if (((grp_read_fu_174_p2 == 32'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp4_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1641)) begin
        if ((ap_phi_mux_last_4_phi_fu_244_p4 == 1'd1)) begin
            ap_phi_reg_pp2_iter0_data_V_9_0_reg_263 <= data_V_9_3_reg_350;
        end else if ((ap_phi_mux_last_4_phi_fu_244_p4 == 1'd0)) begin
            ap_phi_reg_pp2_iter0_data_V_9_0_reg_263 <= p_Result_21_fu_891_p5;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1645)) begin
        if ((last_6_0_reg_252 == 1'd1)) begin
            ap_phi_reg_pp2_iter0_data_V_9_1_reg_297 <= ap_phi_reg_pp2_iter0_data_V_9_0_reg_263;
        end else if ((last_6_0_reg_252 == 1'd0)) begin
            ap_phi_reg_pp2_iter0_data_V_9_1_reg_297 <= p_Result_60_1_fu_925_p5;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1650)) begin
        if ((last_6_1_reg_286 == 1'd1)) begin
            ap_phi_reg_pp2_iter0_data_V_9_2_reg_330 <= ap_phi_reg_pp2_iter0_data_V_9_1_reg_297;
        end else if ((last_6_1_reg_286 == 1'd0)) begin
            ap_phi_reg_pp2_iter0_data_V_9_2_reg_330 <= p_Result_60_2_fu_959_p5;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1641)) begin
        if ((ap_phi_mux_last_4_phi_fu_244_p4 == 1'd1)) begin
            ap_phi_reg_pp2_iter0_user_6_0_reg_274 <= 1'd0;
        end else if ((ap_phi_mux_last_4_phi_fu_244_p4 == 1'd0)) begin
            ap_phi_reg_pp2_iter0_user_6_0_reg_274 <= stream_in_48_TUSER_int_regslice;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1645)) begin
        if ((last_6_0_reg_252 == 1'd1)) begin
            ap_phi_reg_pp2_iter0_user_6_1_reg_308 <= ap_phi_reg_pp2_iter0_user_6_0_reg_274;
        end else if ((last_6_0_reg_252 == 1'd0)) begin
            ap_phi_reg_pp2_iter0_user_6_1_reg_308 <= or_ln72_fu_907_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1650)) begin
        if ((last_6_1_reg_286 == 1'd1)) begin
            ap_phi_reg_pp2_iter0_user_6_2_reg_340 <= ap_phi_reg_pp2_iter0_user_6_1_reg_308;
        end else if ((last_6_1_reg_286 == 1'd0)) begin
            ap_phi_reg_pp2_iter0_user_6_2_reg_340 <= or_ln72_1_fu_941_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1654)) begin
        if ((ap_phi_mux_last_phi_fu_444_p4 == 1'd1)) begin
            ap_phi_reg_pp4_iter0_buffer_V_3_0_reg_463 <= buffer_V_3_3_reg_581;
        end else if ((ap_phi_mux_last_phi_fu_444_p4 == 1'd0)) begin
            ap_phi_reg_pp4_iter0_buffer_V_3_0_reg_463 <= p_Result_s_fu_1032_p5;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1658)) begin
        if ((last_2_0_reg_452 == 1'd1)) begin
            ap_phi_reg_pp4_iter0_buffer_V_3_1_reg_507 <= ap_phi_reg_pp4_iter0_buffer_V_3_0_reg_463;
        end else if ((last_2_0_reg_452 == 1'd0)) begin
            ap_phi_reg_pp4_iter0_buffer_V_3_1_reg_507 <= p_Result_1_fu_1064_p5;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1663)) begin
        if ((last_2_1_reg_496 == 1'd1)) begin
            ap_phi_reg_pp4_iter0_buffer_V_3_2_reg_551 <= ap_phi_reg_pp4_iter0_buffer_V_3_1_reg_507;
        end else if ((last_2_1_reg_496 == 1'd0)) begin
            ap_phi_reg_pp4_iter0_buffer_V_3_2_reg_551 <= p_Result_2_fu_1096_p5;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1654)) begin
        if ((ap_phi_mux_last_phi_fu_444_p4 == 1'd1)) begin
            ap_phi_reg_pp4_iter0_has_last_V_3_0_reg_474 <= has_last_V_3_3_reg_593;
        end else if ((ap_phi_mux_last_phi_fu_444_p4 == 1'd0)) begin
            ap_phi_reg_pp4_iter0_has_last_V_3_0_reg_474 <= tmp_5_fu_1054_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1658)) begin
        if ((last_2_0_reg_452 == 1'd1)) begin
            ap_phi_reg_pp4_iter0_has_last_V_3_1_reg_518 <= ap_phi_reg_pp4_iter0_has_last_V_3_0_reg_474;
        end else if ((last_2_0_reg_452 == 1'd0)) begin
            ap_phi_reg_pp4_iter0_has_last_V_3_1_reg_518 <= tmp_7_fu_1086_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1663)) begin
        if ((last_2_1_reg_496 == 1'd1)) begin
            ap_phi_reg_pp4_iter0_has_last_V_3_2_reg_561 <= ap_phi_reg_pp4_iter0_has_last_V_3_1_reg_518;
        end else if ((last_2_1_reg_496 == 1'd0)) begin
            ap_phi_reg_pp4_iter0_has_last_V_3_2_reg_561 <= tmp_9_fu_1118_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1654)) begin
        if ((ap_phi_mux_last_phi_fu_444_p4 == 1'd1)) begin
            ap_phi_reg_pp4_iter0_has_user_V_3_0_reg_485 <= has_user_V_3_3_reg_605;
        end else if ((ap_phi_mux_last_phi_fu_444_p4 == 1'd0)) begin
            ap_phi_reg_pp4_iter0_has_user_V_3_0_reg_485 <= tmp_4_fu_1044_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1658)) begin
        if ((last_2_0_reg_452 == 1'd1)) begin
            ap_phi_reg_pp4_iter0_has_user_V_3_1_reg_529 <= ap_phi_reg_pp4_iter0_has_user_V_3_0_reg_485;
        end else if ((last_2_0_reg_452 == 1'd0)) begin
            ap_phi_reg_pp4_iter0_has_user_V_3_1_reg_529 <= tmp_6_fu_1076_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1663)) begin
        if ((last_2_1_reg_496 == 1'd1)) begin
            ap_phi_reg_pp4_iter0_has_user_V_3_2_reg_571 <= ap_phi_reg_pp4_iter0_has_user_V_3_1_reg_529;
        end else if ((last_2_1_reg_496 == 1'd0)) begin
            ap_phi_reg_pp4_iter0_has_user_V_3_2_reg_571 <= tmp_8_fu_1108_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_880)) begin
        if (((last_2_2_reg_540 == 1'd1) & (delayed_last_reg_427 == 1'd0))) begin
            buffer_V_3_3_reg_581 <= ap_phi_reg_pp4_iter0_buffer_V_3_2_reg_551;
        end else if (((last_2_2_reg_540 == 1'd0) & (delayed_last_reg_427 == 1'd0))) begin
            buffer_V_3_3_reg_581 <= p_Result_3_fu_1128_p5;
        end else if ((1'b1 == 1'b1)) begin
            buffer_V_3_3_reg_581 <= ap_phi_reg_pp4_iter0_buffer_V_3_3_reg_581;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_824)) begin
        if (((last_6_2_reg_319 == 1'd1) & (delayed_last_1_reg_227 == 1'd0))) begin
            data_V_9_3_reg_350 <= ap_phi_reg_pp2_iter0_data_V_9_2_reg_330;
        end else if (((last_6_2_reg_319 == 1'd0) & (delayed_last_1_reg_227 == 1'd0))) begin
            data_V_9_3_reg_350 <= p_Result_60_3_fu_994_p5;
        end else if ((1'b1 == 1'b1)) begin
            data_V_9_3_reg_350 <= ap_phi_reg_pp2_iter0_data_V_9_3_reg_350;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp2_iter1 == 1'b1) & (delayed_last_1_reg_227 == 1'd0) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001))) begin
        delayed_last_1_reg_227 <= last_4_reg_239;
    end else if (((grp_read_fu_174_p2 == 32'd2) & (1'b1 == ap_CS_fsm_state2))) begin
        delayed_last_1_reg_227 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp4_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage0) & (delayed_last_reg_427 == 1'd0) & (1'b0 == ap_block_pp4_stage0_11001))) begin
        delayed_last_reg_427 <= last_reg_439;
    end else if (((grp_read_fu_174_p2 == 32'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        delayed_last_reg_427 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_880)) begin
        if (((last_2_2_reg_540 == 1'd1) & (delayed_last_reg_427 == 1'd0))) begin
            has_last_V_3_3_reg_593 <= ap_phi_reg_pp4_iter0_has_last_V_3_2_reg_561;
        end else if (((last_2_2_reg_540 == 1'd0) & (delayed_last_reg_427 == 1'd0))) begin
            has_last_V_3_3_reg_593 <= tmp_11_fu_1152_p4;
        end else if ((1'b1 == 1'b1)) begin
            has_last_V_3_3_reg_593 <= ap_phi_reg_pp4_iter0_has_last_V_3_3_reg_593;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_880)) begin
        if (((last_2_2_reg_540 == 1'd1) & (delayed_last_reg_427 == 1'd0))) begin
            has_user_V_3_3_reg_605 <= ap_phi_reg_pp4_iter0_has_user_V_3_2_reg_571;
        end else if (((last_2_2_reg_540 == 1'd0) & (delayed_last_reg_427 == 1'd0))) begin
            has_user_V_3_3_reg_605 <= tmp_10_fu_1141_p4;
        end else if ((1'b1 == 1'b1)) begin
            has_user_V_3_3_reg_605 <= ap_phi_reg_pp4_iter0_has_user_V_3_3_reg_605;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_847)) begin
        if (((ap_phi_mux_last_phi_fu_444_p4 == 1'd1) & (ap_phi_mux_delayed_last_phi_fu_431_p4 == 1'd0))) begin
            last_2_0_reg_452 <= 1'd1;
        end else if (((ap_phi_mux_last_phi_fu_444_p4 == 1'd0) & (ap_phi_mux_delayed_last_phi_fu_431_p4 == 1'd0))) begin
            last_2_0_reg_452 <= stream_in_48_TLAST_int_regslice;
        end else if ((1'b1 == 1'b1)) begin
            last_2_0_reg_452 <= ap_phi_reg_pp4_iter0_last_2_0_reg_452;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_854)) begin
        if (((last_2_0_reg_452 == 1'd1) & (delayed_last_reg_427 == 1'd0))) begin
            last_2_1_reg_496 <= 1'd1;
        end else if (((last_2_0_reg_452 == 1'd0) & (delayed_last_reg_427 == 1'd0))) begin
            last_2_1_reg_496 <= stream_in_48_TLAST_int_regslice;
        end else if ((1'b1 == 1'b1)) begin
            last_2_1_reg_496 <= ap_phi_reg_pp4_iter0_last_2_1_reg_496;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_867)) begin
        if (((last_2_1_reg_496 == 1'd1) & (delayed_last_reg_427 == 1'd0))) begin
            last_2_2_reg_540 <= 1'd1;
        end else if (((last_2_1_reg_496 == 1'd0) & (delayed_last_reg_427 == 1'd0))) begin
            last_2_2_reg_540 <= stream_in_48_TLAST_int_regslice;
        end else if ((1'b1 == 1'b1)) begin
            last_2_2_reg_540 <= ap_phi_reg_pp4_iter0_last_2_2_reg_540;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_880)) begin
        if (((last_2_2_reg_540 == 1'd1) & (delayed_last_reg_427 == 1'd0))) begin
            last_2_3_reg_617 <= 1'd1;
        end else if (((last_2_2_reg_540 == 1'd0) & (delayed_last_reg_427 == 1'd0))) begin
            last_2_3_reg_617 <= stream_in_48_TLAST_int_regslice;
        end else if ((1'b1 == 1'b1)) begin
            last_2_3_reg_617 <= ap_phi_reg_pp4_iter0_last_2_3_reg_617;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp2_iter1 == 1'b1) & (delayed_last_1_reg_227 == 1'd0) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001))) begin
        last_4_reg_239 <= last_6_3_reg_377;
    end else if (((grp_read_fu_174_p2 == 32'd2) & (1'b1 == ap_CS_fsm_state2))) begin
        last_4_reg_239 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_571)) begin
        if (((ap_phi_mux_last_4_phi_fu_244_p4 == 1'd1) & (ap_phi_mux_delayed_last_1_phi_fu_231_p4 == 1'd0))) begin
            last_6_0_reg_252 <= 1'd1;
        end else if (((ap_phi_mux_last_4_phi_fu_244_p4 == 1'd0) & (ap_phi_mux_delayed_last_1_phi_fu_231_p4 == 1'd0))) begin
            last_6_0_reg_252 <= stream_in_48_TLAST_int_regslice;
        end else if ((1'b1 == 1'b1)) begin
            last_6_0_reg_252 <= ap_phi_reg_pp2_iter0_last_6_0_reg_252;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_799)) begin
        if (((last_6_0_reg_252 == 1'd1) & (delayed_last_1_reg_227 == 1'd0))) begin
            last_6_1_reg_286 <= 1'd1;
        end else if (((last_6_0_reg_252 == 1'd0) & (delayed_last_1_reg_227 == 1'd0))) begin
            last_6_1_reg_286 <= stream_in_48_TLAST_int_regslice;
        end else if ((1'b1 == 1'b1)) begin
            last_6_1_reg_286 <= ap_phi_reg_pp2_iter0_last_6_1_reg_286;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_810)) begin
        if (((last_6_1_reg_286 == 1'd1) & (delayed_last_1_reg_227 == 1'd0))) begin
            last_6_2_reg_319 <= 1'd1;
        end else if (((last_6_1_reg_286 == 1'd0) & (delayed_last_1_reg_227 == 1'd0))) begin
            last_6_2_reg_319 <= stream_in_48_TLAST_int_regslice;
        end else if ((1'b1 == 1'b1)) begin
            last_6_2_reg_319 <= ap_phi_reg_pp2_iter0_last_6_2_reg_319;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_824)) begin
        if (((last_6_2_reg_319 == 1'd1) & (delayed_last_1_reg_227 == 1'd0))) begin
            last_6_3_reg_377 <= 1'd1;
        end else if (((last_6_2_reg_319 == 1'd0) & (delayed_last_1_reg_227 == 1'd0))) begin
            last_6_3_reg_377 <= stream_in_48_TLAST_int_regslice;
        end else if ((1'b1 == 1'b1)) begin
            last_6_3_reg_377 <= ap_phi_reg_pp2_iter0_last_6_3_reg_377;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp4_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage0) & (delayed_last_reg_427 == 1'd0) & (1'b0 == ap_block_pp4_stage0_11001))) begin
        last_reg_439 <= last_2_3_reg_617;
    end else if (((grp_read_fu_174_p2 == 32'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        last_reg_439 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == alpha_0_ack_out) & (1'b1 == 1'b1) & (1'b1 == alpha_0_vld_reg)) | ((1'b0 == alpha_0_vld_reg) & (1'b1 == 1'b1)))) begin
        alpha_0_data_reg <= alpha;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        alpha_read_reg_1238 <= alpha_0_data_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        empty_36_reg_1288_3 <= stream_in_48_TUSER_int_regslice;
        p_Result_5_reg_1298 <= {{stream_in_48_TDATA_int_regslice[39:24]}};
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        empty_38_reg_1248_3 <= stream_in_48_TUSER_int_regslice;
        p_Result_10_reg_1263 <= {{stream_in_48_TDATA_int_regslice[31:24]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp4_stage0) & (1'b0 == ap_block_pp4_stage0_11001))) begin
        last_reg_439_pp4_iter1_reg <= last_reg_439;
    end
end

always @ (posedge ap_clk) begin
    if ((((mode_0_ack_out == 1'b1) & (1'b1 == 1'b1) & (mode_0_vld_reg == 1'b1)) | ((1'b1 == 1'b1) & (mode_0_vld_reg == 1'b0)))) begin
        mode_0_data_reg <= mode;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_Result_11_reg_1268 <= {{out_c2_V_fu_733_p2[8:1]}};
        p_Result_s_40_reg_1258 <= {{out_c1_V_fu_719_p2[8:1]}};
        trunc_ln674_1_reg_1253 <= trunc_ln674_1_fu_739_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((last_reg_439 == 1'd0) & (1'b1 == ap_CS_fsm_pp4_stage3) & (delayed_last_reg_427 == 1'd0) & (1'b0 == ap_block_pp4_stage3_11001))) begin
        p_Result_48_1_reg_1423 <= {{ap_phi_mux_buffer_V_3_3_phi_fu_585_p4[127:64]}};
        p_Result_48_2_reg_1438 <= {{ap_phi_mux_buffer_V_3_3_phi_fu_585_p4[191:128]}};
        p_Result_49_1_reg_1428 <= ap_phi_mux_has_user_V_3_3_phi_fu_609_p4[4'd1];
        p_Result_49_2_reg_1443 <= ap_phi_mux_has_user_V_3_3_phi_fu_609_p4[4'd2];
        p_Result_50_1_reg_1433 <= ap_phi_mux_has_last_V_3_3_phi_fu_597_p4[4'd2];
        p_Result_50_2_reg_1448 <= ap_phi_mux_has_last_V_3_3_phi_fu_597_p4[4'd3];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        trunc_ln215_reg_1293 <= trunc_ln215_fu_846_p1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state6) & (regslice_both_stream_out_64_V_data_V_U_apdone_blk == 1'b0)))) begin
        alpha_0_ack_out = 1'b1;
    end else begin
        alpha_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if (((grp_fu_683_p1 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
        ap_condition_pp0_flush_enable = 1'b1;
    end else begin
        ap_condition_pp0_flush_enable = 1'b0;
    end
end

always @ (*) begin
    if (((grp_fu_683_p1 == 1'd1) & (1'b1 == ap_CS_fsm_pp1_stage1) & (1'b0 == ap_block_pp1_stage1_subdone))) begin
        ap_condition_pp1_flush_enable = 1'b1;
    end else begin
        ap_condition_pp1_flush_enable = 1'b0;
    end
end

always @ (*) begin
    if ((ap_phi_mux_delayed_last_1_phi_fu_231_p4 == 1'd1)) begin
        ap_condition_pp2_exit_iter0_state10 = 1'b1;
    end else begin
        ap_condition_pp2_exit_iter0_state10 = 1'b0;
    end
end

always @ (*) begin
    if (((grp_fu_683_p1 == 1'd1) & (1'b1 == ap_CS_fsm_pp3_stage0) & (1'b0 == ap_block_pp3_stage0_subdone))) begin
        ap_condition_pp3_flush_enable = 1'b1;
    end else begin
        ap_condition_pp3_flush_enable = 1'b0;
    end
end

always @ (*) begin
    if ((ap_phi_mux_delayed_last_phi_fu_431_p4 == 1'd1)) begin
        ap_condition_pp4_exit_iter0_state19 = 1'b1;
    end else begin
        ap_condition_pp4_exit_iter0_state19 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter1 == 1'b0) & (ap_enable_reg_pp1_iter0 == 1'b0))) begin
        ap_idle_pp1 = 1'b1;
    end else begin
        ap_idle_pp1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp2_iter1 == 1'b0) & (ap_enable_reg_pp2_iter0 == 1'b0))) begin
        ap_idle_pp2 = 1'b1;
    end else begin
        ap_idle_pp2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter1 == 1'b0) & (ap_enable_reg_pp3_iter0 == 1'b0))) begin
        ap_idle_pp3 = 1'b1;
    end else begin
        ap_idle_pp3 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp4_iter0 == 1'b0) & (ap_enable_reg_pp4_iter1 == 1'b0))) begin
        ap_idle_pp4 = 1'b1;
    end else begin
        ap_idle_pp4 = 1'b0;
    end
end

always @ (*) begin
    if ((delayed_last_reg_427 == 1'd0)) begin
        if ((last_2_2_reg_540 == 1'd1)) begin
            ap_phi_mux_buffer_V_3_3_phi_fu_585_p4 = ap_phi_reg_pp4_iter0_buffer_V_3_2_reg_551;
        end else if ((last_2_2_reg_540 == 1'd0)) begin
            ap_phi_mux_buffer_V_3_3_phi_fu_585_p4 = p_Result_3_fu_1128_p5;
        end else begin
            ap_phi_mux_buffer_V_3_3_phi_fu_585_p4 = ap_phi_reg_pp4_iter0_buffer_V_3_3_reg_581;
        end
    end else begin
        ap_phi_mux_buffer_V_3_3_phi_fu_585_p4 = ap_phi_reg_pp4_iter0_buffer_V_3_3_reg_581;
    end
end

always @ (*) begin
    if ((delayed_last_1_reg_227 == 1'd0)) begin
        if ((last_6_2_reg_319 == 1'd1)) begin
            ap_phi_mux_data_V_9_3_phi_fu_355_p4 = ap_phi_reg_pp2_iter0_data_V_9_2_reg_330;
        end else if ((last_6_2_reg_319 == 1'd0)) begin
            ap_phi_mux_data_V_9_3_phi_fu_355_p4 = p_Result_60_3_fu_994_p5;
        end else begin
            ap_phi_mux_data_V_9_3_phi_fu_355_p4 = ap_phi_reg_pp2_iter0_data_V_9_3_reg_350;
        end
    end else begin
        ap_phi_mux_data_V_9_3_phi_fu_355_p4 = ap_phi_reg_pp2_iter0_data_V_9_3_reg_350;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp2_iter1 == 1'b1) & (delayed_last_1_reg_227 == 1'd0) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0))) begin
        ap_phi_mux_delayed_last_1_phi_fu_231_p4 = last_4_reg_239;
    end else begin
        ap_phi_mux_delayed_last_1_phi_fu_231_p4 = delayed_last_1_reg_227;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp4_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage0) & (delayed_last_reg_427 == 1'd0) & (1'b0 == ap_block_pp4_stage0))) begin
        ap_phi_mux_delayed_last_phi_fu_431_p4 = last_reg_439;
    end else begin
        ap_phi_mux_delayed_last_phi_fu_431_p4 = delayed_last_reg_427;
    end
end

always @ (*) begin
    if ((delayed_last_reg_427 == 1'd0)) begin
        if ((last_2_2_reg_540 == 1'd1)) begin
            ap_phi_mux_has_last_V_3_3_phi_fu_597_p4 = ap_phi_reg_pp4_iter0_has_last_V_3_2_reg_561;
        end else if ((last_2_2_reg_540 == 1'd0)) begin
            ap_phi_mux_has_last_V_3_3_phi_fu_597_p4 = tmp_11_fu_1152_p4;
        end else begin
            ap_phi_mux_has_last_V_3_3_phi_fu_597_p4 = ap_phi_reg_pp4_iter0_has_last_V_3_3_reg_593;
        end
    end else begin
        ap_phi_mux_has_last_V_3_3_phi_fu_597_p4 = ap_phi_reg_pp4_iter0_has_last_V_3_3_reg_593;
    end
end

always @ (*) begin
    if ((delayed_last_reg_427 == 1'd0)) begin
        if ((last_2_2_reg_540 == 1'd1)) begin
            ap_phi_mux_has_user_V_3_3_phi_fu_609_p4 = ap_phi_reg_pp4_iter0_has_user_V_3_2_reg_571;
        end else if ((last_2_2_reg_540 == 1'd0)) begin
            ap_phi_mux_has_user_V_3_3_phi_fu_609_p4 = tmp_10_fu_1141_p4;
        end else begin
            ap_phi_mux_has_user_V_3_3_phi_fu_609_p4 = ap_phi_reg_pp4_iter0_has_user_V_3_3_reg_605;
        end
    end else begin
        ap_phi_mux_has_user_V_3_3_phi_fu_609_p4 = ap_phi_reg_pp4_iter0_has_user_V_3_3_reg_605;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp2_iter1 == 1'b1) & (delayed_last_1_reg_227 == 1'd0) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0))) begin
        ap_phi_mux_last_4_phi_fu_244_p4 = last_6_3_reg_377;
    end else begin
        ap_phi_mux_last_4_phi_fu_244_p4 = last_4_reg_239;
    end
end

always @ (*) begin
    if ((delayed_last_1_reg_227 == 1'd0)) begin
        if ((last_6_2_reg_319 == 1'd1)) begin
            ap_phi_mux_last_6_3_phi_fu_382_p4 = 1'd1;
        end else if ((last_6_2_reg_319 == 1'd0)) begin
            ap_phi_mux_last_6_3_phi_fu_382_p4 = stream_in_48_TLAST_int_regslice;
        end else begin
            ap_phi_mux_last_6_3_phi_fu_382_p4 = ap_phi_reg_pp2_iter0_last_6_3_reg_377;
        end
    end else begin
        ap_phi_mux_last_6_3_phi_fu_382_p4 = ap_phi_reg_pp2_iter0_last_6_3_reg_377;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp4_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage0) & (delayed_last_reg_427 == 1'd0) & (1'b0 == ap_block_pp4_stage0))) begin
        ap_phi_mux_last_phi_fu_444_p4 = last_2_3_reg_617;
    end else begin
        ap_phi_mux_last_phi_fu_444_p4 = last_reg_439;
    end
end

always @ (*) begin
    if ((delayed_last_1_reg_227 == 1'd0)) begin
        if ((last_6_2_reg_319 == 1'd1)) begin
            ap_phi_mux_user_6_3_phi_fu_368_p4 = ap_phi_reg_pp2_iter0_user_6_2_reg_340;
        end else if ((last_6_2_reg_319 == 1'd0)) begin
            ap_phi_mux_user_6_3_phi_fu_368_p4 = or_ln72_2_fu_975_p2;
        end else begin
            ap_phi_mux_user_6_3_phi_fu_368_p4 = ap_phi_reg_pp2_iter0_user_6_3_reg_364;
        end
    end else begin
        ap_phi_mux_user_6_3_phi_fu_368_p4 = ap_phi_reg_pp2_iter0_user_6_3_reg_364;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state6) & (regslice_both_stream_out_64_V_data_V_U_apdone_blk == 1'b0)))) begin
        mode_0_ack_out = 1'b1;
    end else begin
        mode_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp4_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage0) & (ap_phi_mux_last_phi_fu_444_p4 == 1'd0) & (ap_phi_mux_delayed_last_phi_fu_431_p4 == 1'd0) & (1'b0 == ap_block_pp4_stage0)) | ((ap_enable_reg_pp4_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage3) & (last_2_2_reg_540 == 1'd0) & (delayed_last_reg_427 == 1'd0) & (1'b0 == ap_block_pp4_stage3)) | ((ap_enable_reg_pp4_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage2) & (last_2_1_reg_496 == 1'd0) & (delayed_last_reg_427 == 1'd0) & (1'b0 == ap_block_pp4_stage2)) | ((ap_enable_reg_pp4_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage1) & (last_2_0_reg_452 == 1'd0) & (delayed_last_reg_427 == 1'd0) & (1'b0 == ap_block_pp4_stage1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1) & (1'b0 == ap_block_pp1_stage1)) | ((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0)) | ((last_6_2_reg_319 == 1'd0) & (delayed_last_1_reg_227 == 1'd0) & (1'b1 == ap_CS_fsm_pp2_stage3) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b0 == ap_block_pp2_stage3)) | ((last_6_1_reg_286 == 1'd0) & (delayed_last_1_reg_227 == 1'd0) & (1'b1 == ap_CS_fsm_pp2_stage2) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b0 == ap_block_pp2_stage2)) | ((last_6_0_reg_252 == 1'd0) & (delayed_last_1_reg_227 == 1'd0) & (1'b1 == ap_CS_fsm_pp2_stage1) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b0 == ap_block_pp2_stage1)) | ((1'b1 == ap_CS_fsm_pp2_stage0) & (ap_phi_mux_last_4_phi_fu_244_p4 == 1'd0) & (ap_phi_mux_delayed_last_1_phi_fu_231_p4 == 1'd0) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b0 == ap_block_pp2_stage0)) | ((1'b1 == ap_CS_fsm_pp3_stage0) & (ap_enable_reg_pp3_iter0 == 1'b1) & (1'b0 == ap_block_pp3_stage0)))) begin
        stream_in_48_TDATA_blk_n = stream_in_48_TVALID_int_regslice;
    end else begin
        stream_in_48_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp4_iter0 == 1'b1) & (ap_predicate_op249_read_state22 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage3) & (1'b0 == ap_block_pp4_stage3_11001)) | ((ap_enable_reg_pp4_iter0 == 1'b1) & (ap_predicate_op236_read_state21 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage2) & (1'b0 == ap_block_pp4_stage2_11001)) | ((ap_enable_reg_pp4_iter0 == 1'b1) & (ap_predicate_op223_read_state20 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage1) & (1'b0 == ap_block_pp4_stage1_11001)) | ((ap_enable_reg_pp4_iter0 == 1'b1) & (ap_predicate_op209_read_state19 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage0) & (1'b0 == ap_block_pp4_stage0_11001)) | ((ap_predicate_op169_read_state13 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage3) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b0 == ap_block_pp2_stage3_11001)) | ((ap_predicate_op155_read_state12 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage2) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b0 == ap_block_pp2_stage2_11001)) | ((ap_predicate_op141_read_state11 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b0 == ap_block_pp2_stage1_11001)) | ((ap_predicate_op127_read_state10 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b0 == ap_block_pp2_stage0_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1) & (1'b0 == ap_block_pp1_stage1_11001)) | ((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)) | ((1'b1 == ap_CS_fsm_pp3_stage0) & (ap_enable_reg_pp3_iter0 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)))) begin
        stream_in_48_TREADY_int_regslice = 1'b1;
    end else begin
        stream_in_48_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp4_iter0 == 1'b1) & (last_reg_439 == 1'd0) & (1'b1 == ap_CS_fsm_pp4_stage3) & (delayed_last_reg_427 == 1'd0) & (1'b0 == ap_block_pp4_stage3)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0)) | ((ap_enable_reg_pp2_iter1 == 1'b1) & (last_4_reg_239 == 1'd0) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0)) | ((last_4_reg_239 == 1'd0) & (delayed_last_1_reg_227 == 1'd0) & (1'b1 == ap_CS_fsm_pp2_stage3) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b0 == ap_block_pp2_stage3)) | ((ap_enable_reg_pp3_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0) & (1'b0 == ap_block_pp3_stage0)) | ((last_reg_439_pp4_iter1_reg == 1'd0) & (ap_enable_reg_pp4_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage2) & (1'b0 == ap_block_pp4_stage2)) | ((last_reg_439_pp4_iter1_reg == 1'd0) & (ap_enable_reg_pp4_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage1) & (1'b0 == ap_block_pp4_stage1)) | ((ap_enable_reg_pp4_iter1 == 1'b1) & (last_reg_439 == 1'd0) & (1'b1 == ap_CS_fsm_pp4_stage0) & (1'b0 == ap_block_pp4_stage0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1)) | ((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1) & (1'b0 == ap_block_pp1_stage1)) | ((1'b1 == ap_CS_fsm_pp3_stage0) & (ap_enable_reg_pp3_iter0 == 1'b1) & (1'b0 == ap_block_pp3_stage0)))) begin
        stream_out_64_TDATA_blk_n = stream_out_64_TREADY_int_regslice;
    end else begin
        stream_out_64_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((last_reg_439_pp4_iter1_reg == 1'd0) & (ap_enable_reg_pp4_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage1) & (1'b0 == ap_block_pp4_stage1_01001))) begin
        stream_out_64_TDATA_int_regslice = p_Result_48_2_reg_1438;
    end else if (((ap_enable_reg_pp4_iter1 == 1'b1) & (last_reg_439 == 1'd0) & (1'b1 == ap_CS_fsm_pp4_stage0) & (1'b0 == ap_block_pp4_stage0_01001))) begin
        stream_out_64_TDATA_int_regslice = p_Result_48_1_reg_1423;
    end else if (((ap_enable_reg_pp4_iter0 == 1'b1) & (ap_predicate_op265_write_state22 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage3) & (1'b0 == ap_block_pp4_stage3_01001))) begin
        stream_out_64_TDATA_int_regslice = trunc_ln674_7_fu_1163_p1;
    end else if (((1'b1 == ap_CS_fsm_pp3_stage0) & (ap_enable_reg_pp3_iter0 == 1'b1) & (1'b0 == ap_block_pp3_stage0_01001))) begin
        stream_out_64_TDATA_int_regslice = p_Result_24_fu_1021_p5;
    end else if (((ap_predicate_op183_write_state13 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage3) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b0 == ap_block_pp2_stage3_01001))) begin
        stream_out_64_TDATA_int_regslice = ap_phi_mux_data_V_9_3_phi_fu_355_p4;
    end else if (((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1) & (1'b0 == ap_block_pp1_stage1_01001))) begin
        stream_out_64_TDATA_int_regslice = p_Result_64_1_fu_868_p5;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_01001))) begin
        stream_out_64_TDATA_int_regslice = p_Result_25_fu_829_p9;
    end else begin
        stream_out_64_TDATA_int_regslice = 'bx;
    end
end

always @ (*) begin
    if (((last_reg_439_pp4_iter1_reg == 1'd0) & (ap_enable_reg_pp4_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage1) & (1'b0 == ap_block_pp4_stage1_01001))) begin
        stream_out_64_TLAST_int_regslice = p_Result_50_2_reg_1448;
    end else if (((ap_enable_reg_pp4_iter1 == 1'b1) & (last_reg_439 == 1'd0) & (1'b1 == ap_CS_fsm_pp4_stage0) & (1'b0 == ap_block_pp4_stage0_01001))) begin
        stream_out_64_TLAST_int_regslice = p_Result_50_1_reg_1433;
    end else if (((ap_enable_reg_pp4_iter0 == 1'b1) & (ap_predicate_op265_write_state22 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage3) & (1'b0 == ap_block_pp4_stage3_01001))) begin
        stream_out_64_TLAST_int_regslice = ap_phi_mux_has_last_V_3_3_phi_fu_597_p4[4'd1];
    end else if (((ap_predicate_op183_write_state13 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage3) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b0 == ap_block_pp2_stage3_01001))) begin
        stream_out_64_TLAST_int_regslice = ap_phi_mux_last_6_3_phi_fu_382_p4;
    end else if ((((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_01001)) | ((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1) & (1'b0 == ap_block_pp1_stage1_01001)) | ((1'b1 == ap_CS_fsm_pp3_stage0) & (ap_enable_reg_pp3_iter0 == 1'b1) & (1'b0 == ap_block_pp3_stage0_01001)))) begin
        stream_out_64_TLAST_int_regslice = stream_in_48_TLAST_int_regslice;
    end else begin
        stream_out_64_TLAST_int_regslice = 'bx;
    end
end

always @ (*) begin
    if (((last_reg_439_pp4_iter1_reg == 1'd0) & (ap_enable_reg_pp4_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage1) & (1'b0 == ap_block_pp4_stage1_01001))) begin
        stream_out_64_TUSER_int_regslice = p_Result_49_2_reg_1443;
    end else if (((ap_enable_reg_pp4_iter1 == 1'b1) & (last_reg_439 == 1'd0) & (1'b1 == ap_CS_fsm_pp4_stage0) & (1'b0 == ap_block_pp4_stage0_01001))) begin
        stream_out_64_TUSER_int_regslice = p_Result_49_1_reg_1428;
    end else if (((ap_enable_reg_pp4_iter0 == 1'b1) & (ap_predicate_op265_write_state22 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage3) & (1'b0 == ap_block_pp4_stage3_01001))) begin
        stream_out_64_TUSER_int_regslice = ap_phi_mux_has_user_V_3_3_phi_fu_609_p4[4'd0];
    end else if (((1'b1 == ap_CS_fsm_pp3_stage0) & (ap_enable_reg_pp3_iter0 == 1'b1) & (1'b0 == ap_block_pp3_stage0_01001))) begin
        stream_out_64_TUSER_int_regslice = stream_in_48_TUSER_int_regslice;
    end else if (((ap_predicate_op183_write_state13 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage3) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b0 == ap_block_pp2_stage3_01001))) begin
        stream_out_64_TUSER_int_regslice = ap_phi_mux_user_6_3_phi_fu_368_p4;
    end else if (((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1) & (1'b0 == ap_block_pp1_stage1_01001))) begin
        stream_out_64_TUSER_int_regslice = or_ln93_fu_857_p2;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_01001))) begin
        stream_out_64_TUSER_int_regslice = or_ln111_fu_770_p2;
    end else begin
        stream_out_64_TUSER_int_regslice = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp4_iter0 == 1'b1) & (ap_predicate_op265_write_state22 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage3) & (1'b0 == ap_block_pp4_stage3_11001)) | ((ap_predicate_op183_write_state13 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage3) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b0 == ap_block_pp2_stage3_11001)) | ((last_reg_439_pp4_iter1_reg == 1'd0) & (ap_enable_reg_pp4_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage1) & (1'b0 == ap_block_pp4_stage1_11001)) | ((ap_enable_reg_pp4_iter1 == 1'b1) & (last_reg_439 == 1'd0) & (1'b1 == ap_CS_fsm_pp4_stage0) & (1'b0 == ap_block_pp4_stage0_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1) & (1'b0 == ap_block_pp1_stage1_11001)) | ((1'b1 == ap_CS_fsm_pp3_stage0) & (ap_enable_reg_pp3_iter0 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)))) begin
        stream_out_64_TVALID_int_regslice = 1'b1;
    end else begin
        stream_out_64_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state2 : begin
            if (((grp_read_fu_174_p2 == 32'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_pp4_stage0;
            end else if (((grp_read_fu_174_p2 == 32'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_pp3_stage0;
            end else if (((grp_read_fu_174_p2 == 32'd2) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end else if (((grp_read_fu_174_p2 == 32'd3) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else if (((grp_read_fu_174_p2 == 32'd4) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_enable_reg_pp0_iter1 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (regslice_both_stream_out_64_V_data_V_U_apdone_blk == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_pp1_stage0 : begin
            if ((~((ap_enable_reg_pp1_iter1 == 1'b1) & (ap_enable_reg_pp1_iter0 == 1'b0) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_subdone)) & (1'b0 == ap_block_pp1_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage1;
            end else if (((ap_enable_reg_pp1_iter1 == 1'b1) & (ap_enable_reg_pp1_iter0 == 1'b0) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end
        end
        ap_ST_fsm_pp1_stage1 : begin
            if ((1'b0 == ap_block_pp1_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage1;
            end
        end
        ap_ST_fsm_pp2_stage0 : begin
            if ((~((ap_phi_mux_delayed_last_1_phi_fu_231_p4 == 1'd1) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b0 == ap_block_pp2_stage0_subdone)) & (1'b0 == ap_block_pp2_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage1;
            end else if (((ap_phi_mux_delayed_last_1_phi_fu_231_p4 == 1'd1) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b0 == ap_block_pp2_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end
        end
        ap_ST_fsm_pp2_stage1 : begin
            if ((1'b0 == ap_block_pp2_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage1;
            end
        end
        ap_ST_fsm_pp2_stage2 : begin
            if ((1'b0 == ap_block_pp2_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage2;
            end
        end
        ap_ST_fsm_pp2_stage3 : begin
            if ((1'b0 == ap_block_pp2_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage3;
            end
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_pp3_stage0 : begin
            if (~((ap_enable_reg_pp3_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0) & (ap_enable_reg_pp3_iter0 == 1'b0) & (1'b0 == ap_block_pp3_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp3_stage0;
            end else if (((ap_enable_reg_pp3_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0) & (ap_enable_reg_pp3_iter0 == 1'b0) & (1'b0 == ap_block_pp3_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp3_stage0;
            end
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_pp4_stage0 : begin
            if ((~((ap_enable_reg_pp4_iter0 == 1'b1) & (ap_enable_reg_pp4_iter1 == 1'b0) & (ap_phi_mux_delayed_last_phi_fu_431_p4 == 1'd1) & (1'b0 == ap_block_pp4_stage0_subdone)) & (1'b0 == ap_block_pp4_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp4_stage1;
            end else if (((ap_enable_reg_pp4_iter0 == 1'b1) & (ap_enable_reg_pp4_iter1 == 1'b0) & (ap_phi_mux_delayed_last_phi_fu_431_p4 == 1'd1) & (1'b0 == ap_block_pp4_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state26;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp4_stage0;
            end
        end
        ap_ST_fsm_pp4_stage1 : begin
            if ((1'b0 == ap_block_pp4_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp4_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp4_stage1;
            end
        end
        ap_ST_fsm_pp4_stage2 : begin
            if ((~((ap_enable_reg_pp4_iter0 == 1'b0) & (ap_enable_reg_pp4_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage2) & (1'b0 == ap_block_pp4_stage2_subdone)) & (1'b0 == ap_block_pp4_stage2_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp4_stage3;
            end else if (((ap_enable_reg_pp4_iter0 == 1'b0) & (ap_enable_reg_pp4_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage2) & (1'b0 == ap_block_pp4_stage2_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state26;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp4_stage2;
            end
        end
        ap_ST_fsm_pp4_stage3 : begin
            if ((1'b0 == ap_block_pp4_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp4_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp4_stage3;
            end
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp1_stage0 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_pp1_stage1 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_pp2_stage0 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_pp2_stage1 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_pp2_stage2 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_pp2_stage3 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_pp3_stage0 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_pp4_stage0 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_pp4_stage1 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_pp4_stage2 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_pp4_stage3 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd4];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (stream_out_64_TREADY_int_regslice == 1'b0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (stream_in_48_TVALID_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter1 == 1'b1) & (stream_out_64_TREADY_int_regslice == 1'b0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (stream_in_48_TVALID_int_regslice == 1'b0)));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_01001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((stream_out_64_TREADY_int_regslice == 1'b0) | (stream_in_48_TVALID_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage1_11001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((stream_out_64_TREADY_int_regslice == 1'b0) | (stream_in_48_TVALID_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((stream_out_64_TREADY_int_regslice == 1'b0) | (stream_in_48_TVALID_int_regslice == 1'b0)));
end

assign ap_block_pp1_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp1_stage0_11001 = (((ap_enable_reg_pp1_iter1 == 1'b1) & (stream_out_64_TREADY_int_regslice == 1'b0)) | ((ap_enable_reg_pp1_iter0 == 1'b1) & (stream_in_48_TVALID_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_pp1_stage0_subdone = (((ap_enable_reg_pp1_iter1 == 1'b1) & (stream_out_64_TREADY_int_regslice == 1'b0)) | ((ap_enable_reg_pp1_iter0 == 1'b1) & (stream_in_48_TVALID_int_regslice == 1'b0)));
end

assign ap_block_pp1_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp1_stage1_01001 = ((ap_enable_reg_pp1_iter0 == 1'b1) & ((stream_out_64_TREADY_int_regslice == 1'b0) | (stream_in_48_TVALID_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_pp1_stage1_11001 = ((ap_enable_reg_pp1_iter0 == 1'b1) & ((stream_out_64_TREADY_int_regslice == 1'b0) | (stream_in_48_TVALID_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_pp1_stage1_subdone = ((ap_enable_reg_pp1_iter0 == 1'b1) & ((stream_out_64_TREADY_int_regslice == 1'b0) | (stream_in_48_TVALID_int_regslice == 1'b0)));
end

assign ap_block_pp2_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp2_stage0_11001 = (((ap_predicate_op127_read_state10 == 1'b1) & (ap_enable_reg_pp2_iter0 == 1'b1) & (stream_in_48_TVALID_int_regslice == 1'b0)) | ((ap_enable_reg_pp2_iter1 == 1'b1) & ((1'b1 == ap_block_state14_io) | ((last_4_reg_239 == 1'd0) & (stream_out_64_TREADY_int_regslice == 1'b0)))));
end

always @ (*) begin
    ap_block_pp2_stage0_subdone = (((ap_predicate_op127_read_state10 == 1'b1) & (ap_enable_reg_pp2_iter0 == 1'b1) & (stream_in_48_TVALID_int_regslice == 1'b0)) | ((ap_enable_reg_pp2_iter1 == 1'b1) & ((1'b1 == ap_block_state14_io) | ((last_4_reg_239 == 1'd0) & (stream_out_64_TREADY_int_regslice == 1'b0)))));
end

assign ap_block_pp2_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp2_stage1_11001 = ((ap_predicate_op141_read_state11 == 1'b1) & (ap_enable_reg_pp2_iter0 == 1'b1) & (stream_in_48_TVALID_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_pp2_stage1_subdone = ((ap_predicate_op141_read_state11 == 1'b1) & (ap_enable_reg_pp2_iter0 == 1'b1) & (stream_in_48_TVALID_int_regslice == 1'b0));
end

assign ap_block_pp2_stage2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp2_stage2_11001 = ((ap_predicate_op155_read_state12 == 1'b1) & (ap_enable_reg_pp2_iter0 == 1'b1) & (stream_in_48_TVALID_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_pp2_stage2_subdone = ((ap_predicate_op155_read_state12 == 1'b1) & (ap_enable_reg_pp2_iter0 == 1'b1) & (stream_in_48_TVALID_int_regslice == 1'b0));
end

assign ap_block_pp2_stage3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp2_stage3_01001 = ((ap_enable_reg_pp2_iter0 == 1'b1) & (((ap_predicate_op183_write_state13 == 1'b1) & (stream_out_64_TREADY_int_regslice == 1'b0)) | ((ap_predicate_op169_read_state13 == 1'b1) & (stream_in_48_TVALID_int_regslice == 1'b0))));
end

always @ (*) begin
    ap_block_pp2_stage3_11001 = ((ap_enable_reg_pp2_iter0 == 1'b1) & ((1'b1 == ap_block_state13_io) | ((ap_predicate_op183_write_state13 == 1'b1) & (stream_out_64_TREADY_int_regslice == 1'b0)) | ((ap_predicate_op169_read_state13 == 1'b1) & (stream_in_48_TVALID_int_regslice == 1'b0))));
end

always @ (*) begin
    ap_block_pp2_stage3_subdone = ((ap_enable_reg_pp2_iter0 == 1'b1) & ((1'b1 == ap_block_state13_io) | ((ap_predicate_op183_write_state13 == 1'b1) & (stream_out_64_TREADY_int_regslice == 1'b0)) | ((ap_predicate_op169_read_state13 == 1'b1) & (stream_in_48_TVALID_int_regslice == 1'b0))));
end

assign ap_block_pp3_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp3_stage0_01001 = (((ap_enable_reg_pp3_iter1 == 1'b1) & (stream_out_64_TREADY_int_regslice == 1'b0)) | ((ap_enable_reg_pp3_iter0 == 1'b1) & ((stream_out_64_TREADY_int_regslice == 1'b0) | (stream_in_48_TVALID_int_regslice == 1'b0))));
end

always @ (*) begin
    ap_block_pp3_stage0_11001 = (((ap_enable_reg_pp3_iter1 == 1'b1) & (stream_out_64_TREADY_int_regslice == 1'b0)) | ((ap_enable_reg_pp3_iter0 == 1'b1) & ((stream_out_64_TREADY_int_regslice == 1'b0) | (stream_in_48_TVALID_int_regslice == 1'b0))));
end

always @ (*) begin
    ap_block_pp3_stage0_subdone = (((ap_enable_reg_pp3_iter1 == 1'b1) & (stream_out_64_TREADY_int_regslice == 1'b0)) | ((ap_enable_reg_pp3_iter0 == 1'b1) & ((stream_out_64_TREADY_int_regslice == 1'b0) | (stream_in_48_TVALID_int_regslice == 1'b0))));
end

assign ap_block_pp4_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp4_stage0_01001 = (((ap_enable_reg_pp4_iter0 == 1'b1) & (ap_predicate_op209_read_state19 == 1'b1) & (stream_in_48_TVALID_int_regslice == 1'b0)) | ((ap_enable_reg_pp4_iter1 == 1'b1) & (last_reg_439 == 1'd0) & (stream_out_64_TREADY_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_pp4_stage0_11001 = (((ap_enable_reg_pp4_iter0 == 1'b1) & (ap_predicate_op209_read_state19 == 1'b1) & (stream_in_48_TVALID_int_regslice == 1'b0)) | ((ap_enable_reg_pp4_iter1 == 1'b1) & ((1'b1 == ap_block_state23_io) | ((last_reg_439 == 1'd0) & (stream_out_64_TREADY_int_regslice == 1'b0)))));
end

always @ (*) begin
    ap_block_pp4_stage0_subdone = (((ap_enable_reg_pp4_iter0 == 1'b1) & (ap_predicate_op209_read_state19 == 1'b1) & (stream_in_48_TVALID_int_regslice == 1'b0)) | ((ap_enable_reg_pp4_iter1 == 1'b1) & ((1'b1 == ap_block_state23_io) | ((last_reg_439 == 1'd0) & (stream_out_64_TREADY_int_regslice == 1'b0)))));
end

assign ap_block_pp4_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp4_stage1_01001 = (((ap_enable_reg_pp4_iter0 == 1'b1) & (ap_predicate_op223_read_state20 == 1'b1) & (stream_in_48_TVALID_int_regslice == 1'b0)) | ((last_reg_439_pp4_iter1_reg == 1'd0) & (ap_enable_reg_pp4_iter1 == 1'b1) & (stream_out_64_TREADY_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_pp4_stage1_11001 = (((ap_enable_reg_pp4_iter0 == 1'b1) & (ap_predicate_op223_read_state20 == 1'b1) & (stream_in_48_TVALID_int_regslice == 1'b0)) | ((ap_enable_reg_pp4_iter1 == 1'b1) & ((1'b1 == ap_block_state24_io) | ((last_reg_439_pp4_iter1_reg == 1'd0) & (stream_out_64_TREADY_int_regslice == 1'b0)))));
end

always @ (*) begin
    ap_block_pp4_stage1_subdone = (((ap_enable_reg_pp4_iter0 == 1'b1) & (ap_predicate_op223_read_state20 == 1'b1) & (stream_in_48_TVALID_int_regslice == 1'b0)) | ((ap_enable_reg_pp4_iter1 == 1'b1) & ((1'b1 == ap_block_state24_io) | ((last_reg_439_pp4_iter1_reg == 1'd0) & (stream_out_64_TREADY_int_regslice == 1'b0)))));
end

assign ap_block_pp4_stage2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp4_stage2_11001 = (((ap_enable_reg_pp4_iter0 == 1'b1) & (ap_predicate_op236_read_state21 == 1'b1) & (stream_in_48_TVALID_int_regslice == 1'b0)) | ((ap_enable_reg_pp4_iter1 == 1'b1) & ((1'b1 == ap_block_state25_io) | ((last_reg_439_pp4_iter1_reg == 1'd0) & (stream_out_64_TREADY_int_regslice == 1'b0)))));
end

always @ (*) begin
    ap_block_pp4_stage2_subdone = (((ap_enable_reg_pp4_iter0 == 1'b1) & (ap_predicate_op236_read_state21 == 1'b1) & (stream_in_48_TVALID_int_regslice == 1'b0)) | ((ap_enable_reg_pp4_iter1 == 1'b1) & ((1'b1 == ap_block_state25_io) | ((last_reg_439_pp4_iter1_reg == 1'd0) & (stream_out_64_TREADY_int_regslice == 1'b0)))));
end

assign ap_block_pp4_stage3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp4_stage3_01001 = ((ap_enable_reg_pp4_iter0 == 1'b1) & (((ap_predicate_op265_write_state22 == 1'b1) & (stream_out_64_TREADY_int_regslice == 1'b0)) | ((ap_predicate_op249_read_state22 == 1'b1) & (stream_in_48_TVALID_int_regslice == 1'b0))));
end

always @ (*) begin
    ap_block_pp4_stage3_11001 = ((ap_enable_reg_pp4_iter0 == 1'b1) & ((1'b1 == ap_block_state22_io) | ((ap_predicate_op265_write_state22 == 1'b1) & (stream_out_64_TREADY_int_regslice == 1'b0)) | ((ap_predicate_op249_read_state22 == 1'b1) & (stream_in_48_TVALID_int_regslice == 1'b0))));
end

always @ (*) begin
    ap_block_pp4_stage3_subdone = ((ap_enable_reg_pp4_iter0 == 1'b1) & ((1'b1 == ap_block_state22_io) | ((ap_predicate_op265_write_state22 == 1'b1) & (stream_out_64_TREADY_int_regslice == 1'b0)) | ((ap_predicate_op249_read_state22 == 1'b1) & (stream_in_48_TVALID_int_regslice == 1'b0))));
end

always @ (*) begin
    ap_block_state10_pp2_stage0_iter0 = ((ap_predicate_op127_read_state10 == 1'b1) & (stream_in_48_TVALID_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state11_pp2_stage1_iter0 = ((ap_predicate_op141_read_state11 == 1'b1) & (stream_in_48_TVALID_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state12_pp2_stage2_iter0 = ((ap_predicate_op155_read_state12 == 1'b1) & (stream_in_48_TVALID_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state13_io = ((ap_predicate_op183_write_state13 == 1'b1) & (stream_out_64_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state13_pp2_stage3_iter0 = (((ap_predicate_op183_write_state13 == 1'b1) & (stream_out_64_TREADY_int_regslice == 1'b0)) | ((ap_predicate_op169_read_state13 == 1'b1) & (stream_in_48_TVALID_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_state14_io = ((last_4_reg_239 == 1'd0) & (stream_out_64_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state14_pp2_stage0_iter1 = ((last_4_reg_239 == 1'd0) & (stream_out_64_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state16_pp3_stage0_iter0 = ((stream_out_64_TREADY_int_regslice == 1'b0) | (stream_in_48_TVALID_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state17_pp3_stage0_iter1 = (stream_out_64_TREADY_int_regslice == 1'b0);
end

always @ (*) begin
    ap_block_state19_pp4_stage0_iter0 = ((ap_predicate_op209_read_state19 == 1'b1) & (stream_in_48_TVALID_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state20_pp4_stage1_iter0 = ((ap_predicate_op223_read_state20 == 1'b1) & (stream_in_48_TVALID_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state21_pp4_stage2_iter0 = ((ap_predicate_op236_read_state21 == 1'b1) & (stream_in_48_TVALID_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state22_io = ((ap_predicate_op265_write_state22 == 1'b1) & (stream_out_64_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state22_pp4_stage3_iter0 = (((ap_predicate_op265_write_state22 == 1'b1) & (stream_out_64_TREADY_int_regslice == 1'b0)) | ((ap_predicate_op249_read_state22 == 1'b1) & (stream_in_48_TVALID_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_state23_io = ((last_reg_439 == 1'd0) & (stream_out_64_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state23_pp4_stage0_iter1 = ((last_reg_439 == 1'd0) & (stream_out_64_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state24_io = ((last_reg_439_pp4_iter1_reg == 1'd0) & (stream_out_64_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state24_pp4_stage1_iter1 = ((last_reg_439_pp4_iter1_reg == 1'd0) & (stream_out_64_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state25_io = ((last_reg_439_pp4_iter1_reg == 1'd0) & (stream_out_64_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state25_pp4_stage2_iter1 = ((last_reg_439_pp4_iter1_reg == 1'd0) & (stream_out_64_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter0 = (stream_in_48_TVALID_int_regslice == 1'b0);
end

always @ (*) begin
    ap_block_state4_pp0_stage1_iter0 = ((stream_out_64_TREADY_int_regslice == 1'b0) | (stream_in_48_TVALID_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state5_pp0_stage0_iter1 = (stream_out_64_TREADY_int_regslice == 1'b0);
end

always @ (*) begin
    ap_block_state7_pp1_stage0_iter0 = (stream_in_48_TVALID_int_regslice == 1'b0);
end

always @ (*) begin
    ap_block_state8_pp1_stage1_iter0 = ((stream_out_64_TREADY_int_regslice == 1'b0) | (stream_in_48_TVALID_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state9_pp1_stage0_iter1 = (stream_out_64_TREADY_int_regslice == 1'b0);
end

always @ (*) begin
    ap_condition_1641 = ((1'b1 == ap_CS_fsm_pp2_stage0) & (ap_phi_mux_delayed_last_1_phi_fu_231_p4 == 1'd0) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b0 == ap_block_pp2_stage0_11001));
end

always @ (*) begin
    ap_condition_1645 = ((delayed_last_1_reg_227 == 1'd0) & (1'b1 == ap_CS_fsm_pp2_stage1) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b0 == ap_block_pp2_stage1_11001));
end

always @ (*) begin
    ap_condition_1650 = ((delayed_last_1_reg_227 == 1'd0) & (1'b1 == ap_CS_fsm_pp2_stage2) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b0 == ap_block_pp2_stage2_11001));
end

always @ (*) begin
    ap_condition_1654 = ((ap_enable_reg_pp4_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage0) & (ap_phi_mux_delayed_last_phi_fu_431_p4 == 1'd0) & (1'b0 == ap_block_pp4_stage0_11001));
end

always @ (*) begin
    ap_condition_1658 = ((ap_enable_reg_pp4_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage1) & (delayed_last_reg_427 == 1'd0) & (1'b0 == ap_block_pp4_stage1_11001));
end

always @ (*) begin
    ap_condition_1663 = ((ap_enable_reg_pp4_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage2) & (delayed_last_reg_427 == 1'd0) & (1'b0 == ap_block_pp4_stage2_11001));
end

always @ (*) begin
    ap_condition_571 = ((1'b1 == ap_CS_fsm_pp2_stage0) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b0 == ap_block_pp2_stage0_11001));
end

always @ (*) begin
    ap_condition_799 = ((1'b1 == ap_CS_fsm_pp2_stage1) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b0 == ap_block_pp2_stage1_11001));
end

always @ (*) begin
    ap_condition_810 = ((1'b1 == ap_CS_fsm_pp2_stage2) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b0 == ap_block_pp2_stage2_11001));
end

always @ (*) begin
    ap_condition_824 = ((1'b1 == ap_CS_fsm_pp2_stage3) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b0 == ap_block_pp2_stage3_11001));
end

always @ (*) begin
    ap_condition_847 = ((ap_enable_reg_pp4_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage0) & (1'b0 == ap_block_pp4_stage0_11001));
end

always @ (*) begin
    ap_condition_854 = ((ap_enable_reg_pp4_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage1) & (1'b0 == ap_block_pp4_stage1_11001));
end

always @ (*) begin
    ap_condition_867 = ((ap_enable_reg_pp4_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage2) & (1'b0 == ap_block_pp4_stage2_11001));
end

always @ (*) begin
    ap_condition_880 = ((ap_enable_reg_pp4_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage3) & (1'b0 == ap_block_pp4_stage3_11001));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_pp1 = (ap_idle_pp1 ^ 1'b1);

assign ap_enable_pp2 = (ap_idle_pp2 ^ 1'b1);

assign ap_enable_pp3 = (ap_idle_pp3 ^ 1'b1);

assign ap_enable_pp4 = (ap_idle_pp4 ^ 1'b1);

assign ap_phi_reg_pp2_iter0_data_V_9_3_reg_350 = 'bx;

assign ap_phi_reg_pp2_iter0_last_6_0_reg_252 = 'bx;

assign ap_phi_reg_pp2_iter0_last_6_1_reg_286 = 'bx;

assign ap_phi_reg_pp2_iter0_last_6_2_reg_319 = 'bx;

assign ap_phi_reg_pp2_iter0_last_6_3_reg_377 = 'bx;

assign ap_phi_reg_pp2_iter0_user_6_3_reg_364 = 'bx;

assign ap_phi_reg_pp4_iter0_buffer_V_3_3_reg_581 = 'bx;

assign ap_phi_reg_pp4_iter0_has_last_V_3_3_reg_593 = 'bx;

assign ap_phi_reg_pp4_iter0_has_user_V_3_3_reg_605 = 'bx;

assign ap_phi_reg_pp4_iter0_last_2_0_reg_452 = 'bx;

assign ap_phi_reg_pp4_iter0_last_2_1_reg_496 = 'bx;

assign ap_phi_reg_pp4_iter0_last_2_2_reg_540 = 'bx;

assign ap_phi_reg_pp4_iter0_last_2_3_reg_617 = 'bx;

always @ (*) begin
    ap_predicate_op127_read_state10 = ((ap_phi_mux_last_4_phi_fu_244_p4 == 1'd0) & (ap_phi_mux_delayed_last_1_phi_fu_231_p4 == 1'd0));
end

always @ (*) begin
    ap_predicate_op141_read_state11 = ((last_6_0_reg_252 == 1'd0) & (delayed_last_1_reg_227 == 1'd0));
end

always @ (*) begin
    ap_predicate_op155_read_state12 = ((last_6_1_reg_286 == 1'd0) & (delayed_last_1_reg_227 == 1'd0));
end

always @ (*) begin
    ap_predicate_op169_read_state13 = ((last_6_2_reg_319 == 1'd0) & (delayed_last_1_reg_227 == 1'd0));
end

always @ (*) begin
    ap_predicate_op183_write_state13 = ((last_4_reg_239 == 1'd0) & (delayed_last_1_reg_227 == 1'd0));
end

always @ (*) begin
    ap_predicate_op209_read_state19 = ((ap_phi_mux_last_phi_fu_444_p4 == 1'd0) & (ap_phi_mux_delayed_last_phi_fu_431_p4 == 1'd0));
end

always @ (*) begin
    ap_predicate_op223_read_state20 = ((last_2_0_reg_452 == 1'd0) & (delayed_last_reg_427 == 1'd0));
end

always @ (*) begin
    ap_predicate_op236_read_state21 = ((last_2_1_reg_496 == 1'd0) & (delayed_last_reg_427 == 1'd0));
end

always @ (*) begin
    ap_predicate_op249_read_state22 = ((last_2_2_reg_540 == 1'd0) & (delayed_last_reg_427 == 1'd0));
end

always @ (*) begin
    ap_predicate_op265_write_state22 = ((last_reg_439 == 1'd0) & (delayed_last_reg_427 == 1'd0));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_fu_633_p4 = {{stream_in_48_TDATA_int_regslice[15:8]}};

assign grp_fu_643_p4 = {{stream_in_48_TDATA_int_regslice[39:32]}};

assign grp_fu_653_p4 = {{stream_in_48_TDATA_int_regslice[23:16]}};

assign grp_fu_663_p4 = {{stream_in_48_TDATA_int_regslice[47:40]}};

assign grp_fu_673_p4 = {{stream_in_48_TDATA_int_regslice[31:24]}};

assign grp_fu_683_p1 = stream_in_48_TLAST_int_regslice;

assign grp_fu_696_p4 = {{stream_in_48_TDATA_int_regslice[39:24]}};

assign grp_read_fu_174_p2 = mode_0_data_reg;

assign or_ln111_fu_770_p2 = (stream_in_48_TUSER_int_regslice | empty_38_reg_1248_3);

assign or_ln72_1_fu_941_p2 = (stream_in_48_TUSER_int_regslice | ap_phi_reg_pp2_iter0_user_6_1_reg_308);

assign or_ln72_2_fu_975_p2 = (stream_in_48_TUSER_int_regslice | ap_phi_reg_pp2_iter0_user_6_2_reg_340);

assign or_ln72_fu_907_p2 = (stream_in_48_TUSER_int_regslice | ap_phi_reg_pp2_iter0_user_6_0_reg_274);

assign or_ln93_fu_857_p2 = (stream_in_48_TUSER_int_regslice | empty_36_reg_1288_3);

assign out_c1_V_fu_719_p2 = (zext_ln358_1_fu_715_p1 + zext_ln358_fu_711_p1);

assign out_c2_V_fu_733_p2 = (zext_ln358_3_fu_729_p1 + zext_ln358_2_fu_725_p1);

assign out_c3_V_fu_785_p2 = (zext_ln358_5_fu_781_p1 + zext_ln358_4_fu_777_p1);

assign out_c4_V_fu_799_p2 = (zext_ln358_7_fu_795_p1 + zext_ln358_6_fu_791_p1);

assign p_Result_16_fu_809_p4 = {{out_c3_V_fu_785_p2[8:1]}};

assign p_Result_18_fu_819_p4 = {{out_c4_V_fu_799_p2[8:1]}};

assign p_Result_1_fu_1064_p5 = {{ap_phi_reg_pp4_iter0_buffer_V_3_0_reg_463[191:96]}, {stream_in_48_TDATA_int_regslice}, {ap_phi_reg_pp4_iter0_buffer_V_3_0_reg_463[47:0]}};

assign p_Result_21_fu_891_p5 = {{data_V_9_3_reg_350[63:16]}, {tmp_fu_883_p3}};

assign p_Result_24_fu_1021_p5 = {{{{alpha_read_reg_1238}, {p_Result_4_fu_1011_p4}}, {alpha_read_reg_1238}}, {trunc_ln674_fu_1007_p1}};

assign p_Result_25_fu_829_p9 = {{{{{{{{p_Result_18_fu_819_p4}, {grp_fu_673_p4}}, {p_Result_16_fu_809_p4}}, {trunc_ln674_2_fu_805_p1}}, {p_Result_11_reg_1268}}, {p_Result_10_reg_1263}}, {p_Result_s_40_reg_1258}}, {trunc_ln674_1_reg_1253}};

assign p_Result_2_fu_1096_p5 = {{ap_phi_reg_pp4_iter0_buffer_V_3_1_reg_507[191:144]}, {stream_in_48_TDATA_int_regslice}, {ap_phi_reg_pp4_iter0_buffer_V_3_1_reg_507[95:0]}};

assign p_Result_3_fu_1128_p5 = {{stream_in_48_TDATA_int_regslice}, {ap_phi_reg_pp4_iter0_buffer_V_3_2_reg_551[143:0]}};

assign p_Result_4_fu_1011_p4 = {{stream_in_48_TDATA_int_regslice[47:24]}};

assign p_Result_60_1_fu_925_p5 = {{ap_phi_reg_pp2_iter0_data_V_9_0_reg_263[63:32]}, {tmp_1_fu_917_p3}, {ap_phi_reg_pp2_iter0_data_V_9_0_reg_263[15:0]}};

assign p_Result_60_2_fu_959_p5 = {{ap_phi_reg_pp2_iter0_data_V_9_1_reg_297[63:48]}, {tmp_2_fu_951_p3}, {ap_phi_reg_pp2_iter0_data_V_9_1_reg_297[31:0]}};

assign p_Result_60_3_fu_994_p5 = {{tmp_3_fu_986_p3}, {ap_phi_reg_pp2_iter0_data_V_9_2_reg_330[47:0]}};

assign p_Result_64_1_fu_868_p5 = {{{{grp_fu_696_p4}, {trunc_ln215_1_fu_864_p1}}, {p_Result_5_reg_1298}}, {trunc_ln215_reg_1293}};

assign p_Result_s_fu_1032_p5 = {{buffer_V_3_3_reg_581[191:48]}, {stream_in_48_TDATA_int_regslice}};

assign stream_in_48_TREADY = regslice_both_stream_in_48_V_data_V_U_ack_in;

assign stream_out_64_TVALID = regslice_both_stream_out_64_V_data_V_U_vld_out;

assign tmp_10_fu_1141_p4 = {|(stream_in_48_TUSER_int_regslice), ap_phi_reg_pp4_iter0_has_user_V_3_2_reg_571[3 - 1:0]};

assign tmp_11_fu_1152_p4 = {|(stream_in_48_TLAST_int_regslice), ap_phi_reg_pp4_iter0_has_last_V_3_2_reg_561[3 - 1:0]};

assign tmp_1_fu_917_p3 = {{grp_fu_673_p4}, {trunc_ln674_4_fu_913_p1}};

assign tmp_2_fu_951_p3 = {{grp_fu_673_p4}, {trunc_ln674_5_fu_947_p1}};

assign tmp_3_fu_986_p3 = {{grp_fu_673_p4}, {trunc_ln674_6_fu_982_p1}};

assign tmp_4_fu_1044_p4 = {has_user_V_3_3_reg_605[4-1:1], |(stream_in_48_TUSER_int_regslice)};

assign tmp_5_fu_1054_p4 = {has_last_V_3_3_reg_593[4-1:1], |(stream_in_48_TLAST_int_regslice)};

assign tmp_6_fu_1076_p4 = {ap_phi_reg_pp4_iter0_has_user_V_3_0_reg_485[4 - 1:2], |(stream_in_48_TUSER_int_regslice), ap_phi_reg_pp4_iter0_has_user_V_3_0_reg_485[0:0]};

assign tmp_7_fu_1086_p4 = {ap_phi_reg_pp4_iter0_has_last_V_3_0_reg_474[4 - 1:2], |(stream_in_48_TLAST_int_regslice), ap_phi_reg_pp4_iter0_has_last_V_3_0_reg_474[0:0]};

assign tmp_8_fu_1108_p4 = {ap_phi_reg_pp4_iter0_has_user_V_3_1_reg_529[4 - 1:3], |(stream_in_48_TUSER_int_regslice), ap_phi_reg_pp4_iter0_has_user_V_3_1_reg_529[1:0]};

assign tmp_9_fu_1118_p4 = {ap_phi_reg_pp4_iter0_has_last_V_3_1_reg_518[4 - 1:3], |(stream_in_48_TLAST_int_regslice), ap_phi_reg_pp4_iter0_has_last_V_3_1_reg_518[1:0]};

assign tmp_fu_883_p3 = {{grp_fu_673_p4}, {trunc_ln674_3_fu_879_p1}};

assign trunc_ln215_1_fu_864_p1 = stream_in_48_TDATA_int_regslice[15:0];

assign trunc_ln215_fu_846_p1 = stream_in_48_TDATA_int_regslice[15:0];

assign trunc_ln674_1_fu_739_p1 = stream_in_48_TDATA_int_regslice[7:0];

assign trunc_ln674_2_fu_805_p1 = stream_in_48_TDATA_int_regslice[7:0];

assign trunc_ln674_3_fu_879_p1 = stream_in_48_TDATA_int_regslice[7:0];

assign trunc_ln674_4_fu_913_p1 = stream_in_48_TDATA_int_regslice[7:0];

assign trunc_ln674_5_fu_947_p1 = stream_in_48_TDATA_int_regslice[7:0];

assign trunc_ln674_6_fu_982_p1 = stream_in_48_TDATA_int_regslice[7:0];

assign trunc_ln674_7_fu_1163_p1 = ap_phi_mux_buffer_V_3_3_phi_fu_585_p4[63:0];

assign trunc_ln674_fu_1007_p1 = stream_in_48_TDATA_int_regslice[23:0];

assign zext_ln358_1_fu_715_p1 = grp_fu_643_p4;

assign zext_ln358_2_fu_725_p1 = grp_fu_653_p4;

assign zext_ln358_3_fu_729_p1 = grp_fu_663_p4;

assign zext_ln358_4_fu_777_p1 = grp_fu_633_p4;

assign zext_ln358_5_fu_781_p1 = grp_fu_643_p4;

assign zext_ln358_6_fu_791_p1 = grp_fu_653_p4;

assign zext_ln358_7_fu_795_p1 = grp_fu_663_p4;

assign zext_ln358_fu_711_p1 = grp_fu_633_p4;

endmodule //pixel_pack_2
